namespace Client.Assets.Catalogs.DialogueStoring;

internal sealed record DialogueCatalogCreationServices(IDialogueParagraphEffectCreator ParagraphEffectCreator,
    IDialogueOptionAftermathCreator OptionAftermathCreator);