namespace Client.Assets.Catalogs.DialogueStoring;

internal sealed record DialogueCatalogCreationServices(IDialogueParagraphEffectCreator EnvEffectCreator,
    IDialogueOptionAftermathCreator OptionAftermathCreator);