//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GameObjectResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GameObjectResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Client.GameObjectResources", typeof(GameObjectResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abstract monster attack.
        /// </summary>
        internal static string AbstractMonsterAttack {
            get {
                return ResourceManager.GetString("AbstractMonsterAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hawk.
        /// </summary>
        internal static string Archer {
            get {
                return ResourceManager.GetString("Archer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broken arrows.
        /// </summary>
        internal static string ArcherEquipment {
            get {
                return ResourceManager.GetString("ArcherEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mk3 scout power armor.
        /// </summary>
        internal static string ArcherMk3ScoutPowerArmor {
            get {
                return ResourceManager.GetString("ArcherMk3ScoutPowerArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ArcherMk3ScoutPowerArmorDescription {
            get {
                return ResourceManager.GetString("ArcherMk3ScoutPowerArmorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pulsar bow.
        /// </summary>
        internal static string ArcherPulsarBow {
            get {
                return ResourceManager.GetString("ArcherPulsarBow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ArcherPulsarBowDescription {
            get {
                return ResourceManager.GetString("ArcherPulsarBowDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrow rain.
        /// </summary>
        internal static string ArrowRain {
            get {
                return ResourceManager.GetString("ArrowRain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ascetic robe.
        /// </summary>
        internal static string AsceticRobe {
            get {
                return ResourceManager.GetString("AsceticRobe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aspid.
        /// </summary>
        internal static string Aspid {
            get {
                return ResourceManager.GetString("Aspid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haokin.
        /// </summary>
        internal static string Assaulter {
            get {
                return ResourceManager.GetString("Assaulter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battleground.
        /// </summary>
        internal static string Battleground {
            get {
                return ResourceManager.GetString("Battleground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brown bear.
        /// </summary>
        internal static string Bear {
            get {
                return ResourceManager.GetString("Bear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Big monster.
        /// </summary>
        internal static string BigMonster {
            get {
                return ResourceManager.GetString("BigMonster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This monster is big so it has +50% HP and armor x 2..
        /// </summary>
        internal static string BigMonsterDescription {
            get {
                return ResourceManager.GetString("BigMonsterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trooper.
        /// </summary>
        internal static string BlackTrooper {
            get {
                return ResourceManager.GetString("BlackTrooper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blank shot.
        /// </summary>
        internal static string BlankShot {
            get {
                return ResourceManager.GetString("BlankShot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BlankShot_Description {
            get {
                return ResourceManager.GetString("BlankShot_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blind defense.
        /// </summary>
        internal static string BlindDefense {
            get {
                return ResourceManager.GetString("BlindDefense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marauder.
        /// </summary>
        internal static string BoldMarauder {
            get {
                return ResourceManager.GetString("BoldMarauder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The book of a herbs.
        /// </summary>
        internal static string BookOfHerbs {
            get {
                return ResourceManager.GetString("BookOfHerbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BookOfHerbsDescription {
            get {
                return ResourceManager.GetString("BookOfHerbsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The BOSS.
        /// </summary>
        internal static string BossMonster {
            get {
                return ResourceManager.GetString("BossMonster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the Master of the location. The monster is the most powerfull in this part of the world. It has +250% HP and doubled armor..
        /// </summary>
        internal static string BossMonsterDescription {
            get {
                return ResourceManager.GetString("BossMonsterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bring the Beast down.
        /// </summary>
        internal static string BringBeastDown {
            get {
                return ResourceManager.GetString("BringBeastDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BringBeastDown_Description {
            get {
                return ResourceManager.GetString("BringBeastDown_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grim Castle in the Rock.
        /// </summary>
        internal static string Castle {
            get {
                return ResourceManager.GetString("Castle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chaotic neuro-interface.
        /// </summary>
        internal static string ChaoticNeuroInterface {
            get {
                return ResourceManager.GetString("ChaoticNeuroInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is preying.
        /// </summary>
        internal static string CharacterDeepPreyingTitleTemplate {
            get {
                return ResourceManager.GetString("CharacterDeepPreyingTitleTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ninlao Bingwen.
        /// </summary>
        internal static string ChineseOldman {
            get {
                return ResourceManager.GetString("ChineseOldman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese oldman.
        /// </summary>
        internal static string ChineseOldman_Hidden {
            get {
                return ResourceManager.GetString("ChineseOldman_Hidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combat sword.
        /// </summary>
        internal static string CombatSword {
            get {
                return ResourceManager.GetString("CombatSword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CombatSwordDescription {
            get {
                return ResourceManager.GetString("CombatSwordDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sardo.
        /// </summary>
        internal static string Comissar {
            get {
                return ResourceManager.GetString("Comissar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical hit.
        /// </summary>
        internal static string CriticalHit {
            get {
                return ResourceManager.GetString("CriticalHit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ability to deal double damage in 50% cases..
        /// </summary>
        internal static string CriticalHitDescription {
            get {
                return ResourceManager.GetString("CriticalHitDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark light.
        /// </summary>
        internal static string DarkLight {
            get {
                return ResourceManager.GetString("DarkLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Death path.
        /// </summary>
        internal static string DeathPath {
            get {
                return ResourceManager.GetString("DeathPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deceptively light robe.
        /// </summary>
        internal static string DeceptivelyLightRobe {
            get {
                return ResourceManager.GetString("DeceptivelyLightRobe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defense stance.
        /// </summary>
        internal static string DefenseStance {
            get {
                return ResourceManager.GetString("DefenseStance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Somewhere in the Desert....
        /// </summary>
        internal static string Desert {
            get {
                return ResourceManager.GetString("Desert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destroyed village.
        /// </summary>
        internal static string DestroyedVillage {
            get {
                return ResourceManager.GetString("DestroyedVillage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die by the sword.
        /// </summary>
        internal static string DieBySword {
            get {
                return ResourceManager.GetString("DieBySword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DieBySword_Description {
            get {
                return ResourceManager.GetString("DieBySword_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dope herb.
        /// </summary>
        internal static string DopeHerb {
            get {
                return ResourceManager.GetString("DopeHerb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Egyptian Book of a dead.
        /// </summary>
        internal static string EgyptianBookOfDeath {
            get {
                return ResourceManager.GetString("EgyptianBookOfDeath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elite guardsman&apos;s spear.
        /// </summary>
        internal static string EliteGuardsmanSpear {
            get {
                return ResourceManager.GetString("EliteGuardsmanSpear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emptiness in the hand.
        /// </summary>
        internal static string EmptinessInTheHand {
            get {
                return ResourceManager.GetString("EmptinessInTheHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy shot.
        /// </summary>
        internal static string EnergyShot {
            get {
                return ResourceManager.GetString("EnergyShot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evasion.
        /// </summary>
        internal static string Evasion {
            get {
                return ResourceManager.GetString("Evasion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ability to avoid 50% of any attacks..
        /// </summary>
        internal static string EvasionDescription {
            get {
                return ResourceManager.GetString("EvasionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Finger of Anubis.
        /// </summary>
        internal static string FingerOfAnubis {
            get {
                return ResourceManager.GetString("FingerOfAnubis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish a wounded.
        /// </summary>
        internal static string FinishWounded {
            get {
                return ResourceManager.GetString("FinishWounded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FinishWounded_Description {
            get {
                return ResourceManager.GetString("FinishWounded_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grey wolf.
        /// </summary>
        internal static string GreyWolf {
            get {
                return ResourceManager.GetString("GreyWolf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardian woman.
        /// </summary>
        internal static string GuardianWoman {
            get {
                return ResourceManager.GetString("GuardianWoman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Healing salve.
        /// </summary>
        internal static string HealingSalve {
            get {
                return ResourceManager.GetString("HealingSalve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rada The Old.
        /// </summary>
        internal static string Herbalist {
            get {
                return ResourceManager.GetString("Herbalist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wild herbs.
        /// </summary>
        internal static string HerbalistEquipment {
            get {
                return ResourceManager.GetString("HerbalistEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herb bag.
        /// </summary>
        internal static string HerbBag {
            get {
                return ResourceManager.GetString("HerbBag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string HerbBagDescription {
            get {
                return ResourceManager.GetString("HerbBagDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hermitage.
        /// </summary>
        internal static string Hermitage {
            get {
                return ResourceManager.GetString("Hermitage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hit from the shoulder.
        /// </summary>
        internal static string HitFromShoulder {
            get {
                return ResourceManager.GetString("HitFromShoulder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string HitFromShoulder_Description {
            get {
                return ResourceManager.GetString("HitFromShoulder_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leonidas.
        /// </summary>
        internal static string Hoplite {
            get {
                return ResourceManager.GetString("Hoplite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horned frog.
        /// </summary>
        internal static string HornedFrog {
            get {
                return ResourceManager.GetString("HornedFrog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HQ.
        /// </summary>
        internal static string Hq {
            get {
                return ResourceManager.GetString("Hq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Hunt has begun!.
        /// </summary>
        internal static string Hunt {
            get {
                return ResourceManager.GetString("Hunt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Hunt_Description {
            get {
                return ResourceManager.GetString("Hunt_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Improved armor.
        /// </summary>
        internal static string ImprovedArmor {
            get {
                return ResourceManager.GetString("ImprovedArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of the armor increased by 2 times..
        /// </summary>
        internal static string ImprovedArmorDescription {
            get {
                return ResourceManager.GetString("ImprovedArmorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Improved hit points.
        /// </summary>
        internal static string ImprovedHitPoints {
            get {
                return ResourceManager.GetString("ImprovedHitPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of the hit points increased by 2 times..
        /// </summary>
        internal static string ImprovedHitPointsDescription {
            get {
                return ResourceManager.GetString("ImprovedHitPointsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspirational breakthrough.
        /// </summary>
        internal static string InspirationalBreakthrough {
            get {
                return ResourceManager.GetString("InspirationalBreakthrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string InspirationalBreakthrough_Description {
            get {
                return ResourceManager.GetString("InspirationalBreakthrough_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspiring rush.
        /// </summary>
        internal static string InspiringRush {
            get {
                return ResourceManager.GetString("InspiringRush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Juggernaut heavy power armor.
        /// </summary>
        internal static string JuggernautHeavyPowerArmor {
            get {
                return ResourceManager.GetString("JuggernautHeavyPowerArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just hit a whild boar with the knife.
        /// </summary>
        internal static string JustHitBoarWithKnife {
            get {
                return ResourceManager.GetString("JustHitBoarWithKnife", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string JustHitBoarWithKnife_Description {
            get {
                return ResourceManager.GetString("JustHitBoarWithKnife_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Look out!.
        /// </summary>
        internal static string LookOut {
            get {
                return ResourceManager.GetString("LookOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string LookOut_Description {
            get {
                return ResourceManager.GetString("LookOut_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marauder.
        /// </summary>
        internal static string Marauder {
            get {
                return ResourceManager.GetString("Marauder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mass heal.
        /// </summary>
        internal static string MassHeal {
            get {
                return ResourceManager.GetString("MassHeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gelik.
        /// </summary>
        internal static string Medjay {
            get {
                return ResourceManager.GetString("Medjay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Mines.
        /// </summary>
        internal static string Mines {
            get {
                return ResourceManager.GetString("Mines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mk2 medium power armor.
        /// </summary>
        internal static string Mk2MediumPowerArmor {
            get {
                return ResourceManager.GetString("Mk2MediumPowerArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Mk2MediumPowerArmorDescription {
            get {
                return ResourceManager.GetString("Mk2MediumPowerArmorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monastery in the flames.
        /// </summary>
        internal static string Monastery {
            get {
                return ResourceManager.GetString("Monastery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maosin.
        /// </summary>
        internal static string Monk {
            get {
                return ResourceManager.GetString("Monk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nano-metal long cloths.
        /// </summary>
        internal static string NanoMetalLongCloths {
            get {
                return ResourceManager.GetString("NanoMetalLongCloths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old good brawl.
        /// </summary>
        internal static string OldGoodBrawl {
            get {
                return ResourceManager.GetString("OldGoodBrawl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string OldGoodBrawl_Description {
            get {
                return ResourceManager.GetString("OldGoodBrawl_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oldman.
        /// </summary>
        internal static string Oldman {
            get {
                return ResourceManager.GetString("Oldman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paralitic Chor.
        /// </summary>
        internal static string ParaliticChor {
            get {
                return ResourceManager.GetString("ParaliticChor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Pit.
        /// </summary>
        internal static string Pit {
            get {
                return ResourceManager.GetString("Pit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapid shot.
        /// </summary>
        internal static string RapidShot {
            get {
                return ResourceManager.GetString("RapidShot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff of Redemption.
        /// </summary>
        internal static string RedemptionStaff {
            get {
                return ResourceManager.GetString("RedemptionStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rise your swords!.
        /// </summary>
        internal static string RiseYourSwords {
            get {
                return ResourceManager.GetString("RiseYourSwords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string RiseYourSwords_Description {
            get {
                return ResourceManager.GetString("RiseYourSwords_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sabotage.
        /// </summary>
        internal static string Sabotage {
            get {
                return ResourceManager.GetString("Sabotage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Sabotage_Description {
            get {
                return ResourceManager.GetString("Sabotage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scarabeus King&apos;s Leg.
        /// </summary>
        internal static string ScarabeusKingLeg {
            get {
                return ResourceManager.GetString("ScarabeusKingLeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship Graveyard.
        /// </summary>
        internal static string ShipGraveyard {
            get {
                return ResourceManager.GetString("ShipGraveyard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silver wind necklace.
        /// </summary>
        internal static string SilverWindNecklace {
            get {
                return ResourceManager.GetString("SilverWindNecklace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SilverWindNecklaceDescription {
            get {
                return ResourceManager.GetString("SilverWindNecklaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ping.
        /// </summary>
        internal static string Spearman {
            get {
                return ResourceManager.GetString("Spearman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff hits.
        /// </summary>
        internal static string StaffHit {
            get {
                return ResourceManager.GetString("StaffHit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stay strong.
        /// </summary>
        internal static string StayStrong {
            get {
                return ResourceManager.GetString("StayStrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string StayStrong_Description {
            get {
                return ResourceManager.GetString("StayStrong_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stryga.
        /// </summary>
        internal static string Stryga {
            get {
                return ResourceManager.GetString("Stryga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppressive fire.
        /// </summary>
        internal static string SuppressiveFire {
            get {
                return ResourceManager.GetString("SuppressiveFire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surprise maneuver.
        /// </summary>
        internal static string SurpriseManeuver {
            get {
                return ResourceManager.GetString("SurpriseManeuver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SurpriseManeuver_Description {
            get {
                return ResourceManager.GetString("SurpriseManeuver_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Svarog&apos;s Blast Furnace.
        /// </summary>
        internal static string SvarogBlastFurnace {
            get {
                return ResourceManager.GetString("SvarogBlastFurnace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evil swamp.
        /// </summary>
        internal static string Swamp {
            get {
                return ResourceManager.GetString("Swamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Berimir.
        /// </summary>
        internal static string Swordsman {
            get {
                return ResourceManager.GetString("Swordsman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol of the God.
        /// </summary>
        internal static string SymbolOfGod {
            get {
                return ResourceManager.GetString("SymbolOfGod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nafrit.
        /// </summary>
        internal static string Synth {
            get {
                return ResourceManager.GetString("Synth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Lower Caste Synth.
        /// </summary>
        internal static string Synth_Hidden {
            get {
                return ResourceManager.GetString("Synth_Hidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tactical maneuver.
        /// </summary>
        internal static string TacticalManeuver {
            get {
                return ResourceManager.GetString("TacticalManeuver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Thicket.
        /// </summary>
        internal static string Thicket {
            get {
                return ResourceManager.GetString("Thicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toxic gas bomb.
        /// </summary>
        internal static string ToxicGasBomb {
            get {
                return ResourceManager.GetString("ToxicGasBomb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracker&apos;s savvy.
        /// </summary>
        internal static string TrackerSavvy {
            get {
                return ResourceManager.GetString("TrackerSavvy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TrackerSavvy_Description {
            get {
                return ResourceManager.GetString("TrackerSavvy_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vampire bite.
        /// </summary>
        internal static string VampireBite {
            get {
                return ResourceManager.GetString("VampireBite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volkolak.
        /// </summary>
        internal static string Volkolak {
            get {
                return ResourceManager.GetString("Volkolak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volkolak claws.
        /// </summary>
        internal static string VolkolakClaws {
            get {
                return ResourceManager.GetString("VolkolakClaws", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warrior of the Wolf Time.
        /// </summary>
        internal static string VolkolakWarrior {
            get {
                return ResourceManager.GetString("VolkolakWarrior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sword pieces.
        /// </summary>
        internal static string WarriorEquipment {
            get {
                return ResourceManager.GetString("WarriorEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wide sword slash.
        /// </summary>
        internal static string WideSwordSlash {
            get {
                return ResourceManager.GetString("WideSwordSlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will-o-Wisp.
        /// </summary>
        internal static string Wisp {
            get {
                return ResourceManager.GetString("Wisp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Woman short.
        /// </summary>
        internal static string WomanShort {
            get {
                return ResourceManager.GetString("WomanShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string WomanShortDescription {
            get {
                return ResourceManager.GetString("WomanShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wooden hand sculpture.
        /// </summary>
        internal static string WoodenHandSculpture {
            get {
                return ResourceManager.GetString("WoodenHandSculpture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string WoodenHandSculptureDescription {
            get {
                return ResourceManager.GetString("WoodenHandSculptureDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zduhach Might.
        /// </summary>
        internal static string ZduhachMight {
            get {
                return ResourceManager.GetString("ZduhachMight", resourceCulture);
            }
        }
    }
}
