//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rpg.Client {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GameObjectResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GameObjectResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rpg.Client.GameObjectResources", typeof(GameObjectResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aspid.
        /// </summary>
        internal static string Aspid {
            get {
                return ResourceManager.GetString("Aspid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brown bear.
        /// </summary>
        internal static string Bear {
            get {
                return ResourceManager.GetString("Bear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Berimir.
        /// </summary>
        internal static string Berimir {
            get {
                return ResourceManager.GetString("Berimir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grey wolf.
        /// </summary>
        internal static string GreyWolf {
            get {
                return ResourceManager.GetString("GreyWolf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardian woman.
        /// </summary>
        internal static string GuardianWoman {
            get {
                return ResourceManager.GetString("GuardianWoman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hawk.
        /// </summary>
        internal static string Hawk {
            get {
                return ResourceManager.GetString("Hawk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HQ.
        /// </summary>
        internal static string Hq {
            get {
                return ResourceManager.GetString("Hq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Mines.
        /// </summary>
        internal static string Mines {
            get {
                return ResourceManager.GetString("Mines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oldman.
        /// </summary>
        internal static string Oldman {
            get {
                return ResourceManager.GetString("Oldman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Pit.
        /// </summary>
        internal static string Pit {
            get {
                return ResourceManager.GetString("Pit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rada.
        /// </summary>
        internal static string Rada {
            get {
                return ResourceManager.GetString("Rada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Thicket.
        /// </summary>
        internal static string Thicket {
            get {
                return ResourceManager.GetString("Thicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sword pieces.
        /// </summary>
        internal static string WarriorEquipment {
            get {
                return ResourceManager.GetString("WarriorEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will-o-Wisp.
        /// </summary>
        internal static string Wisp {
            get {
                return ResourceManager.GetString("Wisp", resourceCulture);
            }
        }
    }
}
