//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rpg.Client {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PlotResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PlotResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rpg.Client.PlotResources", typeof(PlotResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en[{&quot;Name&quot;:&quot;Slavic1&quot;,&quot;BeforeCombatNode&quot;:{&quot;Speaker&quot;:&quot;\u042D\u043A\u0438\u043F\u0430\u0436 \u0431\u043E\u0435\u0432\u043E\u0439 \u0434\u0440\u0443\u0436\u0438\u043D\u044B \u201C\u041B\u044E\u0442\u0438\u043A\u201D&quot;,&quot;Text&quot;:&quot;\u0413\u043D\u0435\u0437\u0434\u043E \u0430\u0441\u043F\u0438\u0434\u043E\u0432 \u043F\u0440\u044F\u043C\u043E \u043F\u0440\u0435\u0434 \u0442\u043E\u0431\u043E\u0439. \u041D\u0430\u0434\u043E\u0431\u043D\u043E \u0443\u043D\u0438\u0447\u0442\u043E\u0436\u0438\u0442\u044C \u0433\u0430\u0434\ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MainPlot {
            get {
                return ResourceManager.GetString("MainPlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;Name&quot;:&quot;Slavic1&quot;,&quot;BeforeCombatNode&quot;:{&quot;Speaker&quot;:&quot;\u042D\u043A\u0438\u043F\u0430\u0436 \u0431\u043E\u0435\u0432\u043E\u0439 \u0434\u0440\u0443\u0436\u0438\u043D\u044B \u201C\u041B\u044E\u0442\u0438\u043A\u201D&quot;,&quot;Text&quot;:&quot;\u0413\u043D\u0435\u0437\u0434\u043E \u0430\u0441\u043F\u0438\u0434\u043E\u0432 \u043F\u0440\u044F\u043C\u043E \u043F\u0440\u0435\u0434 \u0442\u043E\u0431\u043E\u0439. \u041D\u0430\u0434\u043E\u0431\u043D\u043E \u0443\u043D\u0438\u0447\u0442\u043E\u0436\u0438\u0442\u044C \u0433\u0430\u0434\u0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Plot {
            get {
                return ResourceManager.GetString("Plot", resourceCulture);
            }
        }
    }
}
