//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rpg.Client {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PlotResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PlotResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rpg.Client.PlotResources", typeof(PlotResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;Location&quot;: &quot;Thicket&quot;,
        ///    &quot;Name&quot;: &quot;Р“Р»СѓС…Р°СЏ С‡Р°С‰Р°&quot;,
        ///    &quot;BeforeCombatNode&quot;: {
        ///      &quot;Fragments&quot;: [
        ///        {
        ///          &quot;Speaker&quot;: &quot;Hq&quot;,
        ///          &quot;Text&quot;: &quot;Р“РЅРµР·РґРѕ Р°СЃРїРёРґРѕРІ РїСЂСЏРјРѕ РїСЂРµРґ С‚РѕР±РѕР№. РќР°РґРѕР±РЅРѕ СѓРЅРёС‡С‚РѕР¶РёС‚СЊ РіР°РґРѕРІ&quot;
        ///        },
        ///        {
        ///          &quot;Speaker&quot;: &quot;Berimir&quot;,
        ///          &quot;Text&quot;: &quot;РќРµР±С‹Р»СЊ РєР°РєР°СЏ. Р•С‰С‘ Р¶Рµ РґРµРґ СЃРєР°Р·С‹РІР°Р», РєР°Рє РїРµСЂРµРІРµР»Рё РѕРЅРё Р°СЃРїРёРґРѕРІ&quot;
        ///        },
        ///        {
        ///          &quot;Spe [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MainPlot {
            get {
                return ResourceManager.GetString("MainPlot", resourceCulture);
            }
        }
    }
}
