//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rpg.Client {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UiResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UiResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rpg.Client.UiResource", typeof(UiResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armor: {0}.
        /// </summary>
        internal static string ArmorLabelTemplate {
            get {
                return ResourceManager.GetString("ArmorLabelTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-combat.
        /// </summary>
        internal static string AutocombatButtonTitle {
            get {
                return ResourceManager.GetString("AutocombatButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string BackButtonTitle {
            get {
                return ResourceManager.GetString("BackButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to the map.
        /// </summary>
        internal static string BackToMapMenuButtonTitle {
            get {
                return ResourceManager.GetString("BackToMapMenuButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestiary.
        /// </summary>
        internal static string BestiaryButtonTitle {
            get {
                return ResourceManager.GetString("BestiaryButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lvl.
        /// </summary>
        internal static string BiomeLevelText {
            get {
                return ResourceManager.GetString("BiomeLevelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BiomeTutorialText {
            get {
                return ResourceManager.GetString("BiomeTutorialText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string CloseButtonTitle {
            get {
                return ResourceManager.GetString("CloseButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combat length:.
        /// </summary>
        internal static string CombatLengthLabel {
            get {
                return ResourceManager.GetString("CombatLengthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combat level: {0}.
        /// </summary>
        internal static string CombatLevelTemplate {
            get {
                return ResourceManager.GetString("CombatLevelTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} xp to level up.
        /// </summary>
        internal static string CombatLevelUpTemplate {
            get {
                return ResourceManager.GetString("CombatLevelUpTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combat progress: {0}/{1}.
        /// </summary>
        internal static string CombatProgressTemplate {
            get {
                return ResourceManager.GetString("CombatProgressTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defeat!.
        /// </summary>
        internal static string CombatResultDefeatText {
            get {
                return ResourceManager.GetString("CombatResultDefeatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items found:.
        /// </summary>
        internal static string CombatResultItemsFoundLabel {
            get {
                return ResourceManager.GetString("CombatResultItemsFoundLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monster danger decreased to {0} (on -50%).
        /// </summary>
        internal static string CombatResultMonsterDangerDecreasedTemplate {
            get {
                return ResourceManager.GetString("CombatResultMonsterDangerDecreasedTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monster danger increased to {0}.
        /// </summary>
        internal static string CombatResultMonsterDangerIncreasedTemplate {
            get {
                return ResourceManager.GetString("CombatResultMonsterDangerIncreasedTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next combat....
        /// </summary>
        internal static string CombatResultNextText {
            get {
                return ResourceManager.GetString("CombatResultNextText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Victory!.
        /// </summary>
        internal static string CombatResultVictoryText {
            get {
                return ResourceManager.GetString("CombatResultVictoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CombatTutorialText {
            get {
                return ResourceManager.GetString("CombatTutorialText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue game.
        /// </summary>
        internal static string ContinueGameButtonTitle {
            get {
                return ResourceManager.GetString("ContinueGameButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits.
        /// </summary>
        internal static string CreditsButtonTitle {
            get {
                return ResourceManager.GetString("CreditsButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage: {0} - {1} to {2}.
        /// </summary>
        internal static string DamageEffectRuleText {
            get {
                return ResourceManager.GetString("DamageEffectRuleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage: {0}.
        /// </summary>
        internal static string DamageLabelTemplate {
            get {
                return ResourceManager.GetString("DamageLabelTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase damage of {1}% on {0} on {3} turns.
        /// </summary>
        internal static string DecreaseDamageEffectRuleText {
            get {
                return ResourceManager.GetString("DecreaseDamageEffectRuleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string EventTutorialText {
            get {
                return ResourceManager.GetString("EventTutorialText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit game.
        /// </summary>
        internal static string ExitGameButtonTitle {
            get {
                return ResourceManager.GetString("ExitGameButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formation.
        /// </summary>
        internal static string FormationButtonTitle {
            get {
                return ResourceManager.GetString("FormationButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} combats left.
        /// </summary>
        internal static string GlobalEffectDurationTemplate {
            get {
                return ResourceManager.GetString("GlobalEffectDurationTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heal: {0} - {1} to {2}.
        /// </summary>
        internal static string HealEffectRuleText {
            get {
                return ResourceManager.GetString("HealEffectRuleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment.
        /// </summary>
        internal static string HeroEquipmentInfoTitle {
            get {
                return ResourceManager.GetString("HeroEquipmentInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Info.
        /// </summary>
        internal static string HeroGeneralInfoTitle {
            get {
                return ResourceManager.GetString("HeroGeneralInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perks.
        /// </summary>
        internal static string HeroPerkInfoTitle {
            get {
                return ResourceManager.GetString("HeroPerkInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills.
        /// </summary>
        internal static string HeroSkillsInfoTitle {
            get {
                return ResourceManager.GetString("HeroSkillsInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HitPoints: {0}.
        /// </summary>
        internal static string HitPointsLabelTemplate {
            get {
                return ResourceManager.GetString("HitPointsLabelTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase damage of {1} on {0} on {3} turns.
        /// </summary>
        internal static string IncreaseDamageEffectRuleText {
            get {
                return ResourceManager.GetString("IncreaseDamageEffectRuleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evasion!.
        /// </summary>
        internal static string IndicatorEvasion {
            get {
                return ResourceManager.GetString("IndicatorEvasion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip!.
        /// </summary>
        internal static string IndicatorSkipTurn {
            get {
                return ResourceManager.GetString("IndicatorSkipTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string InfoButtonTitle {
            get {
                return ResourceManager.GetString("InfoButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is training only.
        /// </summary>
        internal static string IsTrainingOnly {
            get {
                return ResourceManager.GetString("IsTrainingOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level Up.
        /// </summary>
        internal static string LevelUpButtonTitle {
            get {
                return ResourceManager.GetString("LevelUpButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw {0} - {1} hp from {2}.
        /// </summary>
        internal static string LifeDrawEffectRuleText {
            get {
                return ResourceManager.GetString("LifeDrawEffectRuleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long.
        /// </summary>
        internal static string LongCombatSequenceText {
            get {
                return ResourceManager.GetString("LongCombatSequenceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mana cost: {0}.
        /// </summary>
        internal static string ManaCostLabelTemplate {
            get {
                return ResourceManager.GetString("ManaCostLabelTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mana: {0}/{1}.
        /// </summary>
        internal static string ManaLabelTemplate {
            get {
                return ResourceManager.GetString("ManaLabelTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        internal static string MediumCombatSequenceText {
            get {
                return ResourceManager.GetString("MediumCombatSequenceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danger of the monsters: {0}.
        /// </summary>
        internal static string MonsterDangerTemplate {
            get {
                return ResourceManager.GetString("MonsterDangerTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lvl.
        /// </summary>
        internal static string MonsterLevelShortText {
            get {
                return ResourceManager.GetString("MonsterLevelShortText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to the pool.
        /// </summary>
        internal static string MoveToThePoolButtonTitle {
            get {
                return ResourceManager.GetString("MoveToThePoolButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party.
        /// </summary>
        internal static string PartyButtonTitle {
            get {
                return ResourceManager.GetString("PartyButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage: {0} - {1} to {2} during {3} turns.
        /// </summary>
        internal static string PeriodicDamageEffectRuleText {
            get {
                return ResourceManager.GetString("PeriodicDamageEffectRuleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heal over time: {0} - {1} during {2} to {3}.
        /// </summary>
        internal static string PeriodicHealEffectRuleText {
            get {
                return ResourceManager.GetString("PeriodicHealEffectRuleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsButtonTitle {
            get {
                return ResourceManager.GetString("SettingsButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short.
        /// </summary>
        internal static string ShortCombatSequenceText {
            get {
                return ResourceManager.GetString("ShortCombatSequenceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all enemies.
        /// </summary>
        internal static string SkillDirectionAllEnemiesText {
            get {
                return ResourceManager.GetString("SkillDirectionAllEnemiesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to self.
        /// </summary>
        internal static string SkillDirectionSelfText {
            get {
                return ResourceManager.GetString("SkillDirectionSelfText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to target.
        /// </summary>
        internal static string SkillDirectionTargetText {
            get {
                return ResourceManager.GetString("SkillDirectionTargetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required {0} psy-energy.
        /// </summary>
        internal static string SkillManaCostTemplate {
            get {
                return ResourceManager.GetString("SkillManaCostTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not show anymore.
        /// </summary>
        internal static string SkipTutorialButtonTitle {
            get {
                return ResourceManager.GetString("SkipTutorialButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New game.
        /// </summary>
        internal static string StartNewGameButtonTitle {
            get {
                return ResourceManager.GetString("StartNewGameButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stun to {1} on {0}.
        /// </summary>
        internal static string StunEffectRuleText {
            get {
                return ResourceManager.GetString("StunEffectRuleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surrender.
        /// </summary>
        internal static string SurrenderButtonTitle {
            get {
                return ResourceManager.GetString("SurrenderButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch fullscreen.
        /// </summary>
        internal static string SwitchFullScreenButtonTitle {
            get {
                return ResourceManager.GetString("SwitchFullScreenButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch lang.
        /// </summary>
        internal static string SwitchLanguageButtonTitle {
            get {
                return ResourceManager.GetString("SwitchLanguageButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To The Combat!.
        /// </summary>
        internal static string ToTheCombatButtonTitle {
            get {
                return ResourceManager.GetString("ToTheCombatButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xp Reward.
        /// </summary>
        internal static string XpRewardText {
            get {
                return ResourceManager.GetString("XpRewardText", resourceCulture);
            }
        }
    }
}
