//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rpg.Client {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UiResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UiResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rpg.Client.UiResource", typeof(UiResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BiomeTutorualText {
            get {
                return ResourceManager.GetString("BiomeTutorualText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CombatTutorualText {
            get {
                return ResourceManager.GetString("CombatTutorualText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 a 1.
        /// </summary>
        internal static string EventPlotSlavicPlot_1_a_1 {
            get {
                return ResourceManager.GetString("EventPlotSlavicPlot_1_a_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 a 2.
        /// </summary>
        internal static string EventPlotSlavicPlot_1_a_2 {
            get {
                return ResourceManager.GetString("EventPlotSlavicPlot_1_a_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string EventPlotSlavicPlot_1_a_3 {
            get {
                return ResourceManager.GetString("EventPlotSlavicPlot_1_a_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 b 1.
        /// </summary>
        internal static string EventPlotSlavicPlot_1_b_1 {
            get {
                return ResourceManager.GetString("EventPlotSlavicPlot_1_b_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string EventPlotSlavicPlot_1_b_2 {
            get {
                return ResourceManager.GetString("EventPlotSlavicPlot_1_b_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string EventPlotSlavicPlot_1_b_3 {
            get {
                return ResourceManager.GetString("EventPlotSlavicPlot_1_b_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string EventPlotSlavicPlot_1_b_4 {
            get {
                return ResourceManager.GetString("EventPlotSlavicPlot_1_b_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string EventPlotSlavicPlot_3_a_1 {
            get {
                return ResourceManager.GetString("EventPlotSlavicPlot_3_a_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string EventPlotSlavicPlot_3_a_2 {
            get {
                return ResourceManager.GetString("EventPlotSlavicPlot_3_a_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string EventPlotSlavicPlot_3_b_1 {
            get {
                return ResourceManager.GetString("EventPlotSlavicPlot_3_b_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string EventSpeakerBerimir {
            get {
                return ResourceManager.GetString("EventSpeakerBerimir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string EventSpeakerHawk {
            get {
                return ResourceManager.GetString("EventSpeakerHawk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string EventSpeakerHq {
            get {
                return ResourceManager.GetString("EventSpeakerHq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string EventTutorualText {
            get {
                return ResourceManager.GetString("EventTutorualText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string StartGameButtonTitle {
            get {
                return ResourceManager.GetString("StartGameButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch lang.
        /// </summary>
        internal static string SwitchLanguageButtonTitle {
            get {
                return ResourceManager.GetString("SwitchLanguageButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch res.
        /// </summary>
        internal static string SwitchResolutionButtonTitle {
            get {
                return ResourceManager.GetString("SwitchResolutionButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sword pieces.
        /// </summary>
        internal static string WarriorEquipmentItemDisplayName {
            get {
                return ResourceManager.GetString("WarriorEquipmentItemDisplayName", resourceCulture);
            }
        }
    }
}
