//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rpg.Client {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UiResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UiResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Rpg.Client.UiResource", typeof(UiResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string StartGameButtonTitle {
            get {
                return ResourceManager.GetString("StartGameButtonTitle", resourceCulture);
            }
        }
        
        internal static string SwitchLanguageButtonTitle {
            get {
                return ResourceManager.GetString("SwitchLanguageButtonTitle", resourceCulture);
            }
        }
        
        internal static string SwitchResolutionButtonTitle {
            get {
                return ResourceManager.GetString("SwitchResolutionButtonTitle", resourceCulture);
            }
        }
        
        internal static string WarriorEquipmentItemDisplayName {
            get {
                return ResourceManager.GetString("WarriorEquipmentItemDisplayName", resourceCulture);
            }
        }
        
        internal static string EventPlotSlavicPlot_1_b_1 {
            get {
                return ResourceManager.GetString("EventPlotSlavicPlot_1_b_1", resourceCulture);
            }
        }
        
        internal static string EventPlotSlavicPlot_1_a_1 {
            get {
                return ResourceManager.GetString("EventPlotSlavicPlot_1_a_1", resourceCulture);
            }
        }
        
        internal static string EventPlotSlavicPlot_1_a_2 {
            get {
                return ResourceManager.GetString("EventPlotSlavicPlot_1_a_2", resourceCulture);
            }
        }
        
        internal static string EventPlotSlavicPlot_3_b_1 {
            get {
                return ResourceManager.GetString("EventPlotSlavicPlot_3_b_1", resourceCulture);
            }
        }
        
        internal static string EventPlotSlavicPlot_3_a_1 {
            get {
                return ResourceManager.GetString("EventPlotSlavicPlot_3_a_1", resourceCulture);
            }
        }
        
        internal static string EventPlotSlavicPlot_3_a_2 {
            get {
                return ResourceManager.GetString("EventPlotSlavicPlot_3_a_2", resourceCulture);
            }
        }
        
        internal static string CombatTutorualText {
            get {
                return ResourceManager.GetString("CombatTutorualText", resourceCulture);
            }
        }
        
        internal static string BiomeTutorualText {
            get {
                return ResourceManager.GetString("BiomeTutorualText", resourceCulture);
            }
        }
        
        internal static string EventTutorualText {
            get {
                return ResourceManager.GetString("EventTutorualText", resourceCulture);
            }
        }
        
        internal static string EventSpeakerHq {
            get {
                return ResourceManager.GetString("EventSpeakerHq", resourceCulture);
            }
        }
        
        internal static string EventSpeakerBerimir {
            get {
                return ResourceManager.GetString("EventSpeakerBerimir", resourceCulture);
            }
        }
        
        internal static string EventSpeakerHawk {
            get {
                return ResourceManager.GetString("EventSpeakerHawk", resourceCulture);
            }
        }
        
        internal static string EventPlotSlavicPlot_1_b_2 {
            get {
                return ResourceManager.GetString("EventPlotSlavicPlot_1_b_2", resourceCulture);
            }
        }
        
        internal static string EventPlotSlavicPlot_1_b_3 {
            get {
                return ResourceManager.GetString("EventPlotSlavicPlot_1_b_3", resourceCulture);
            }
        }
        
        internal static string EventPlotSlavicPlot_1_b_4 {
            get {
                return ResourceManager.GetString("EventPlotSlavicPlot_1_b_4", resourceCulture);
            }
        }
        
        internal static string EventPlotSlavicPlot_1_a_3 {
            get {
                return ResourceManager.GetString("EventPlotSlavicPlot_1_a_3", resourceCulture);
            }
        }
        
        internal static string EventPlotSlavicPlot_2_b_1 {
            get {
                return ResourceManager.GetString("EventPlotSlavicPlot_2_b_1", resourceCulture);
            }
        }
        
        internal static string EventPlotSlavicPlot_2_b_2 {
            get {
                return ResourceManager.GetString("EventPlotSlavicPlot_2_b_2", resourceCulture);
            }
        }
        
        internal static string EventPlotSlavicPlot_2_b_3 {
            get {
                return ResourceManager.GetString("EventPlotSlavicPlot_2_b_3", resourceCulture);
            }
        }
        
        internal static string EventPlotSlavicPlot_2_b_4 {
            get {
                return ResourceManager.GetString("EventPlotSlavicPlot_2_b_4", resourceCulture);
            }
        }
        
        internal static string EventPlotSlavicPlot_2_a_1 {
            get {
                return ResourceManager.GetString("EventPlotSlavicPlot_2_a_1", resourceCulture);
            }
        }
        
        internal static string EventPlotSlavicPlot_2_a_2 {
            get {
                return ResourceManager.GetString("EventPlotSlavicPlot_2_a_2", resourceCulture);
            }
        }
        
        internal static string EventPlotSlavicPlot_2_a_3 {
            get {
                return ResourceManager.GetString("EventPlotSlavicPlot_2_a_3", resourceCulture);
            }
        }
        
        internal static string EventPlotSlavicPlot_2_a_4 {
            get {
                return ResourceManager.GetString("EventPlotSlavicPlot_2_a_4", resourceCulture);
            }
        }
        
        internal static string EventOptionCombatText {
            get {
                return ResourceManager.GetString("EventOptionCombatText", resourceCulture);
            }
        }
        
        internal static string EventOptionContinueText {
            get {
                return ResourceManager.GetString("EventOptionContinueText", resourceCulture);
            }
        }
        
        internal static string EventPlotSlavicPlot_3_b_2 {
            get {
                return ResourceManager.GetString("EventPlotSlavicPlot_3_b_2", resourceCulture);
            }
        }
        
        internal static string EventPlotSlavicPlot_3_b_3 {
            get {
                return ResourceManager.GetString("EventPlotSlavicPlot_3_b_3", resourceCulture);
            }
        }
        
        internal static string EventPlotSlavicPlot_3_b_4 {
            get {
                return ResourceManager.GetString("EventPlotSlavicPlot_3_b_4", resourceCulture);
            }
        }
        
        internal static string EventPlotSlavicPlot_3_b_5 {
            get {
                return ResourceManager.GetString("EventPlotSlavicPlot_3_b_5", resourceCulture);
            }
        }
        
        internal static string EventPlotSlavicPlot_3_a_3 {
            get {
                return ResourceManager.GetString("EventPlotSlavicPlot_3_a_3", resourceCulture);
            }
        }
        
        internal static string EventPlotSlavicPlot_3_a_4 {
            get {
                return ResourceManager.GetString("EventPlotSlavicPlot_3_a_4", resourceCulture);
            }
        }
        
        internal static string EventSpeakerOldman {
            get {
                return ResourceManager.GetString("EventSpeakerOldman", resourceCulture);
            }
        }
        
        internal static string EventSpeakerGuardianWoman {
            get {
                return ResourceManager.GetString("EventSpeakerGuardianWoman", resourceCulture);
            }
        }
        
        internal static string EventPlotSlavicPlot_5_b_1 {
            get {
                return ResourceManager.GetString("EventPlotSlavicPlot_5_b_1", resourceCulture);
            }
        }
        
        internal static string EventPlotSlavicPlot_5_a_1 {
            get {
                return ResourceManager.GetString("EventPlotSlavicPlot_5_a_1", resourceCulture);
            }
        }
        
        internal static string SlavicThicketNodeName {
            get {
                return ResourceManager.GetString("SlavicThicketNodeName", resourceCulture);
            }
        }
        
        internal static string SlavicMinesNodeName {
            get {
                return ResourceManager.GetString("SlavicMinesNodeName", resourceCulture);
            }
        }
        
        internal static string SlavicPitNodeName {
            get {
                return ResourceManager.GetString("SlavicPitNodeName", resourceCulture);
            }
        }
        
        internal static string SettingsButtonTitle {
            get {
                return ResourceManager.GetString("SettingsButtonTitle", resourceCulture);
            }
        }
        
        internal static string SwitchFullScreenButtonTitle {
            get {
                return ResourceManager.GetString("SwitchFullScreenButtonTitle", resourceCulture);
            }
        }
        
        internal static string BackToMainMenuButtonTitle {
            get {
                return ResourceManager.GetString("BackToMainMenuButtonTitle", resourceCulture);
            }
        }
        
        internal static string LoadLastSaveButtonTitle {
            get {
                return ResourceManager.GetString("LoadLastSaveButtonTitle", resourceCulture);
            }
        }
    }
}
