namespace Rpg.Client.Core
{
    internal enum EquipmentSid
    {
        ArcherPulsarBow,
        ArcherMk3ScoutPowerArmor,
        CombatSword,
        Mk2MediumPowerArmor,
        SilverWindNecklace,
        EgyptianBookOfDeath,
        NanoMetalLongCloths,
        ScarabeusKingLeg,
        WomanShort,
        HerbBag,
        BookOfHerbs,
        AsceticRobe,
        SymbolOfGod,
        EliteGuardsmanSpear,
        JuggernautHeavyPowerArmor,
        ChaoticNeuroInterface,
        WoodenHandSculpture,
        EmptinessInTheHand,
        DeceptivelyLightRobe,
        MagicAndMechanicalBox,
        VoiceModulator,
        HiddenExoskeleton,
        NewLawCodexOfFreedom,
        EmberGladius,
        Mk2MediumPowerArmor2,
        BrokenAresSculpture
    }
}