stryker-config:
  ignore-methods:
    - "*Log", # Ignores all methods ending with Log
    - "Console.Write*", # Ignores all methods starting with Write in the class Console
    - "*Exception.ctor" # Ignores all exception constructors
    - "ToString"
    - "ConfigureAwait"
  ignore-mutations:
    - "string"
    - "linq.First",
    - "linq.Sum"