namespace Rpg.Client.Core.Skills
{
    internal enum SkillSid
    {
        Heal,

        ArrowRain,
        EnergyShot,
        DefenseStance,
        DopeHerb,
        MassHeal,
        AbstractMonsterAttack,
        HealingSalve,
        PowerUp,
        SvarogBlastFurnace,
        SwordSlash,
        SwordSlashRandom,
        SwordSlashInaccurate,
        SwordSlashDefensive,
        StaffHit,
        VampireBite,
        VolkolakClaws,
        WideSwordSlash,
        ZduhachMight,
        DarkLighting,
        MummificationTouch,
        ParalyticChoir,
        FingerOfAnubis,
        WispEnergy,
        VolkolakWarriorEnergyBurst,
        RestoreMantra,
        PathOf1000Firsts,
        RapidShot,
        ToxicGas,
        MutantBearBludgeon,
        GodNature,
        MasterStaffHit,
        PenetrationStrike,
        StonePath,
        DemonicTaunt,
        Reproach, // укор в насилии
        NoViolencePlease,
        FaithBoost, // укрепление веры
        AskedNoViolence,
        Motivation,
        FightAgainstMaster,
        BraveHearts,
        Liberation,
        SwordSwing,
        JavelinThrow,
        AresWarBringerThreads,
        PoisonedSpear,
        SuperNaturalAgility,
        Sunburst,
        FlameThrowing,
        PipeBludgeon,
        Demountage,
        CouosLegacy, // Наследие Койоса защищет от монстров при помощи знаний
        PainfullWound,
        ShotOfHate,
        WarCry,
        TribeDefender,
        GroupProtection,
        RifleShot,
        Shotgun
    }
}