//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CreditsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CreditsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Client.CreditsResource", typeof(CreditsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Pavel Kurkutov] @kreghek on telegram.
        /// </summary>
        internal static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special thanks to:
        ///
        ///[Egor Kornev] - for a huge amount of art
        ///[Anatoly Yuzhikov] - for continuous support of the game
        ///[Gregory Kulakov] - for help at the very beginning of development
        ///[Ivan Rakhmanenko] - for finding a cool musical style
        ///[Nikolay Kondratyev] - for the title soundtrack
        ///[Andrey Vedernikov] - for music for fights
        ///
        ///Gratitude for participation in the project
        ///
        ///[KrisWay22] on instagram
        ///[nelocodreh] on telegram
        ///[ZLODEiDOBRODEi] on telegram
        ///[SerCraft] on telegram
        ///[despair73] on VK.
        /// </summary>
        internal static string Credits {
            get {
                return ResourceManager.GetString("Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brown, Black, White, Orange, Wild, Tiger, Snow Leopard, Koo, Kooapps, Gray, Zombie, Gumdrop, Candy, Choco, Darth, Dark, Goldfish on a, Evil, German, Beach, City, Haunted, Spooky.
        /// </summary>
        internal static string NicknameFirstParts {
            get {
                return ResourceManager.GetString("NicknameFirstParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dog, Cat, Dalmation, Bird, Koobird, Goldfish, Turtle, Clyde, Selina, Troy, Oscar, Lily, Skateboard, Swim E Fresh, Pip, Leo, Raph, Donny, Mikey, Man, Sloth, Ferret, Grandpa, Voviboye.
        /// </summary>
        internal static string NicknameSecondParts {
            get {
                return ResourceManager.GetString("NicknameSecondParts", resourceCulture);
            }
        }
    }
}
