//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GameObjectResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GameObjectResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Client.GameObjectResources", typeof(GameObjectResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abstract monster attack.
        /// </summary>
        internal static string AbstractMonsterAttack {
            get {
                return ResourceManager.GetString("AbstractMonsterAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afterlife whirlwind.
        /// </summary>
        internal static string AfterlifeWhirlwind {
            get {
                return ResourceManager.GetString("AfterlifeWhirlwind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deals &lt;damage&gt; to all enemies in the vanguard and moves to the vanguard itself..
        /// </summary>
        internal static string AfterlifeWhirlwind_Description {
            get {
                return ResourceManager.GetString("AfterlifeWhirlwind_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agressor.
        /// </summary>
        internal static string Agressor {
            get {
                return ResourceManager.GetString("Agressor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amazon.
        /// </summary>
        internal static string Amazon {
            get {
                return ResourceManager.GetString("Amazon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambush drone.
        /// </summary>
        internal static string AmbushDrone {
            get {
                return ResourceManager.GetString("AmbushDrone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broken arrows.
        /// </summary>
        internal static string ArcherEquipment {
            get {
                return ResourceManager.GetString("ArcherEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mk3 scout power armor.
        /// </summary>
        internal static string ArcherMk3ScoutPowerArmor {
            get {
                return ResourceManager.GetString("ArcherMk3ScoutPowerArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ArcherMk3ScoutPowerArmorDescription {
            get {
                return ResourceManager.GetString("ArcherMk3ScoutPowerArmorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pulsar bow.
        /// </summary>
        internal static string ArcherPulsarBow {
            get {
                return ResourceManager.GetString("ArcherPulsarBow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ArcherPulsarBowDescription {
            get {
                return ResourceManager.GetString("ArcherPulsarBowDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrow rain.
        /// </summary>
        internal static string ArrowRain {
            get {
                return ResourceManager.GetString("ArrowRain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrow of Morana.
        /// </summary>
        internal static string ArrowsOfMorana {
            get {
                return ResourceManager.GetString("ArrowsOfMorana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deals &lt;damage&gt; to all enemies..
        /// </summary>
        internal static string ArrowsOfMorana_Description {
            get {
                return ResourceManager.GetString("ArrowsOfMorana_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Art of Combat.
        /// </summary>
        internal static string ArtOfCombat {
            get {
                return ResourceManager.GetString("ArtOfCombat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deals &lt;damage&gt; to the closest enemy in the line and inspires all allies in the rear, increasing their &lt;damagebuff&gt; over &lt;duration&gt;..
        /// </summary>
        internal static string ArtOfCombat_Description {
            get {
                return ResourceManager.GetString("ArtOfCombat_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ascetic robe.
        /// </summary>
        internal static string AsceticRobe {
            get {
                return ResourceManager.GetString("AsceticRobe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asked No Violence.
        /// </summary>
        internal static string AskedNoViolence {
            get {
                return ResourceManager.GetString("AskedNoViolence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Sage begins to collect the hidden threat. If someone attacks, it increases the threat by &lt;threat&gt;..
        /// </summary>
        internal static string AskedNoViolence_Description {
            get {
                return ResourceManager.GetString("AskedNoViolence_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aspid.
        /// </summary>
        internal static string Aspid {
            get {
                return ResourceManager.GetString("Aspid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haokin.
        /// </summary>
        internal static string Assaulter {
            get {
                return ResourceManager.GetString("Assaulter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automataur.
        /// </summary>
        internal static string Automataur {
            get {
                return ResourceManager.GetString("Automataur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baltic thunder.
        /// </summary>
        internal static string BalticThunder {
            get {
                return ResourceManager.GetString("BalticThunder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deals &lt;damage&gt; to the closest enemy in the line..
        /// </summary>
        internal static string BalticThunder_Description {
            get {
                return ResourceManager.GetString("BalticThunder_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battleground.
        /// </summary>
        internal static string Battleground {
            get {
                return ResourceManager.GetString("Battleground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Big monster.
        /// </summary>
        internal static string BigMonster {
            get {
                return ResourceManager.GetString("BigMonster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This monster is big so it has +50% HP and armor x 2..
        /// </summary>
        internal static string BigMonsterDescription {
            get {
                return ResourceManager.GetString("BigMonsterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blank shot.
        /// </summary>
        internal static string BlankShot {
            get {
                return ResourceManager.GetString("BlankShot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moves to the vanguard and deals &lt;damage&gt; to the nearest enemy in the line. If the partisan was already in the vanguard, then it deals &lt;bonus_damage&gt;..
        /// </summary>
        internal static string BlankShot_Description {
            get {
                return ResourceManager.GetString("BlankShot_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blind defense.
        /// </summary>
        internal static string BlindDefense {
            get {
                return ResourceManager.GetString("BlindDefense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gain &lt;defense&gt; and fire 5 &lt;damage&gt; shots at random enemies..
        /// </summary>
        internal static string BlindDefense_Description {
            get {
                return ResourceManager.GetString("BlindDefense_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marauder.
        /// </summary>
        internal static string BoldMarauder {
            get {
                return ResourceManager.GetString("BoldMarauder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The book of a herbs.
        /// </summary>
        internal static string BookOfHerbs {
            get {
                return ResourceManager.GetString("BookOfHerbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BookOfHerbsDescription {
            get {
                return ResourceManager.GetString("BookOfHerbsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The BOSS.
        /// </summary>
        internal static string BossMonster {
            get {
                return ResourceManager.GetString("BossMonster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the Master of the location. The monster is the most powerfull in this part of the world. It has +250% HP and doubled armor..
        /// </summary>
        internal static string BossMonsterDescription {
            get {
                return ResourceManager.GetString("BossMonsterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bring the Beast down.
        /// </summary>
        internal static string BringBeastDown {
            get {
                return ResourceManager.GetString("BringBeastDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deals &lt;damage&gt; to the strongest enemy with the mark. And misses the next move..
        /// </summary>
        internal static string BringBeastDown_Description {
            get {
                return ResourceManager.GetString("BringBeastDown_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BuyFood_CrisisAftermath {
            get {
                return ResourceManager.GetString("BuyFood_CrisisAftermath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - done.
        /// </summary>
        internal static string CampaignsJobCompletePatternSid {
            get {
                return ResourceManager.GetString("CampaignsJobCompletePatternSid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1}/{2}.
        /// </summary>
        internal static string CampaignsJobProgressPatternSid {
            get {
                return ResourceManager.GetString("CampaignsJobProgressPatternSid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete any campaigns.
        /// </summary>
        internal static string CampaignsJobTitleSid {
            get {
                return ResourceManager.GetString("CampaignsJobTitleSid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grim Castle in the Rock.
        /// </summary>
        internal static string Castle {
            get {
                return ResourceManager.GetString("Castle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chain hit.
        /// </summary>
        internal static string ChainHit {
            get {
                return ResourceManager.GetString("ChainHit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moves to the vanguard and deals &lt;damage&gt; on the strongest enemy..
        /// </summary>
        internal static string ChainHit_Description {
            get {
                return ResourceManager.GetString("ChainHit_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chaotic neuro-interface.
        /// </summary>
        internal static string ChaoticNeuroInterface {
            get {
                return ResourceManager.GetString("ChaoticNeuroInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is preying.
        /// </summary>
        internal static string CharacterDeepPreyingTitleTemplate {
            get {
                return ResourceManager.GetString("CharacterDeepPreyingTitleTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chasing.
        /// </summary>
        internal static string Chasing {
            get {
                return ResourceManager.GetString("Chasing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Throws a chain forward that deals &lt;damage&gt; and burns &lt;resolve_damage&gt; to the farthest enemy. Then he pulls the enemy into the vanguard..
        /// </summary>
        internal static string Chasing_Description {
            get {
                return ResourceManager.GetString("Chasing_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ninlao Bingwen.
        /// </summary>
        internal static string ChineseOldman {
            get {
                return ResourceManager.GetString("ChineseOldman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese oldman.
        /// </summary>
        internal static string ChineseOldman_Hidden {
            get {
                return ResourceManager.GetString("ChineseOldman_Hidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combat sword.
        /// </summary>
        internal static string CombatSword {
            get {
                return ResourceManager.GetString("CombatSword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CombatSwordDescription {
            get {
                return ResourceManager.GetString("CombatSwordDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - done.
        /// </summary>
        internal static string CommonJobCompletePattern {
            get {
                return ResourceManager.GetString("CommonJobCompletePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1}/{2}.
        /// </summary>
        internal static string CommonJobInProgressPattern {
            get {
                return ResourceManager.GetString("CommonJobInProgressPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrupted bear.
        /// </summary>
        internal static string CorruptedBear {
            get {
                return ResourceManager.GetString("CorruptedBear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cover of Dew.
        /// </summary>
        internal static string CoverOfDew {
            get {
                return ResourceManager.GetString("CoverOfDew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical hit.
        /// </summary>
        internal static string CriticalHit {
            get {
                return ResourceManager.GetString("CriticalHit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ability to deal double damage in 50% cases..
        /// </summary>
        internal static string CriticalHitDescription {
            get {
                return ResourceManager.GetString("CriticalHitDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyber-claws.
        /// </summary>
        internal static string CyberClaws {
            get {
                return ResourceManager.GetString("CyberClaws", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deals &lt;damage&gt; to the closest enemy in the line and moves to the vanguard..
        /// </summary>
        internal static string CyberClaws_Description {
            get {
                return ResourceManager.GetString("CyberClaws_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dance with the Past.
        /// </summary>
        internal static string DanceWithThePast {
            get {
                return ResourceManager.GetString("DanceWithThePast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moves to the vanguard and deals two &lt;damage&gt; hits..
        /// </summary>
        internal static string DanceWithThePast_Description {
            get {
                return ResourceManager.GetString("DanceWithThePast_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark light.
        /// </summary>
        internal static string DarkLight {
            get {
                return ResourceManager.GetString("DarkLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark raids.
        /// </summary>
        internal static string DarkRaids {
            get {
                return ResourceManager.GetString("DarkRaids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moves forward and deals two &lt;damage&gt; hits..
        /// </summary>
        internal static string DarkRaids_Description {
            get {
                return ResourceManager.GetString("DarkRaids_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Death path.
        /// </summary>
        internal static string DeathPath {
            get {
                return ResourceManager.GetString("DeathPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deceptively light robe.
        /// </summary>
        internal static string DeceptivelyLightRobe {
            get {
                return ResourceManager.GetString("DeceptivelyLightRobe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defeat any enemies.
        /// </summary>
        internal static string DefeatAnyEnemies {
            get {
                return ResourceManager.GetString("DefeatAnyEnemies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defeat any enemies during campaign.
        /// </summary>
        internal static string DefeatAnyEnemiesDuringCampaign {
            get {
                return ResourceManager.GetString("DefeatAnyEnemiesDuringCampaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - done.
        /// </summary>
        internal static string DefeatsJobCompletePatternSid {
            get {
                return ResourceManager.GetString("DefeatsJobCompletePatternSid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1}/{2}.
        /// </summary>
        internal static string DefeatsJobProgressPatternSid {
            get {
                return ResourceManager.GetString("DefeatsJobProgressPatternSid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defeats.
        /// </summary>
        internal static string DefeatsJobTitleSid {
            get {
                return ResourceManager.GetString("DefeatsJobTitleSid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Somewhere in the Desert....
        /// </summary>
        internal static string Desert {
            get {
                return ResourceManager.GetString("Desert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destroyed village.
        /// </summary>
        internal static string DestroyedVillage {
            get {
                return ResourceManager.GetString("DestroyedVillage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devastating Paw.
        /// </summary>
        internal static string DevastatingPaw {
            get {
                return ResourceManager.GetString("DevastatingPaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die by the sword.
        /// </summary>
        internal static string DieBySword {
            get {
                return ResourceManager.GetString("DieBySword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moves forward and deals &lt;damage&gt; to the closest enemy in the line..
        /// </summary>
        internal static string DieBySword_Description {
            get {
                return ResourceManager.GetString("DieBySword_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grey.
        /// </summary>
        internal static string DigitalHort {
            get {
                return ResourceManager.GetString("DigitalHort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Talking Hort.
        /// </summary>
        internal static string DigitalHort_Hidden {
            get {
                return ResourceManager.GetString("DigitalHort_Hidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital wolf.
        /// </summary>
        internal static string DigitalWolf {
            get {
                return ResourceManager.GetString("DigitalWolf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dope herb.
        /// </summary>
        internal static string DopeHerb {
            get {
                return ResourceManager.GetString("DopeHerb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double kapesh!.
        /// </summary>
        internal static string DoubleKapesh {
            get {
                return ResourceManager.GetString("DoubleKapesh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moves forward and deals two hits with each &lt;damage&gt; capesh..
        /// </summary>
        internal static string DoubleKapesh_Description {
            get {
                return ResourceManager.GetString("DoubleKapesh_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ebony skin.
        /// </summary>
        internal static string EbonySkin {
            get {
                return ResourceManager.GetString("EbonySkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increases its defense by &lt;defense&gt;. When auto-triggered, increases protection by &lt;defense_auto&gt;..
        /// </summary>
        internal static string EbonySkin_Description {
            get {
                return ResourceManager.GetString("EbonySkin_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Egyptian Book of a dead.
        /// </summary>
        internal static string EgyptianBookOfDeath {
            get {
                return ResourceManager.GetString("EgyptianBookOfDeath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elite guardsman&apos;s spear.
        /// </summary>
        internal static string EliteGuardsmanSpear {
            get {
                return ResourceManager.GetString("EliteGuardsmanSpear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emptiness in the hand.
        /// </summary>
        internal static string EmptinessInTheHand {
            get {
                return ResourceManager.GetString("EmptinessInTheHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energetic bite.
        /// </summary>
        internal static string EnergeticBite {
            get {
                return ResourceManager.GetString("EnergeticBite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deals &lt;damage&gt; to the shields of the most charged enemy and goes to the rearguard..
        /// </summary>
        internal static string EnergeticBite_Description {
            get {
                return ResourceManager.GetString("EnergeticBite_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energetic Superiority.
        /// </summary>
        internal static string EnergeticSuperiority {
            get {
                return ResourceManager.GetString("EnergeticSuperiority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deals &lt;damage&gt; to the shields of the most charged enemy in the rearguard..
        /// </summary>
        internal static string EnergeticSuperiority_Description {
            get {
                return ResourceManager.GetString("EnergeticSuperiority_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evasion.
        /// </summary>
        internal static string Evasion {
            get {
                return ResourceManager.GetString("Evasion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ability to avoid 50% of any attacks..
        /// </summary>
        internal static string EvasionDescription {
            get {
                return ResourceManager.GetString("EvasionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra HP.
        /// </summary>
        internal static string ExtraHitPoints {
            get {
                return ResourceManager.GetString("ExtraHitPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gain additional &lt;hp&gt;.
        /// </summary>
        internal static string ExtraHitPoints_Description {
            get {
                return ResourceManager.GetString("ExtraHitPoints_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra Shields.
        /// </summary>
        internal static string ExtraShieldPoints {
            get {
                return ResourceManager.GetString("ExtraShieldPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gain additional &lt;sp&gt;.
        /// </summary>
        internal static string ExtraShieldPoints_Description {
            get {
                return ResourceManager.GetString("ExtraShieldPoints_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra Speed.
        /// </summary>
        internal static string ExtraSpeed {
            get {
                return ResourceManager.GetString("ExtraSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gain additional &lt;resolve&gt;.
        /// </summary>
        internal static string ExtraSpeed_Description {
            get {
                return ResourceManager.GetString("ExtraSpeed_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eyes of Chaos.
        /// </summary>
        internal static string EyesOfChaos {
            get {
                return ResourceManager.GetString("EyesOfChaos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deals &lt;damage&gt; to all enemies in the vanguard and moves to the vanguard itself..
        /// </summary>
        internal static string EyesOfChaos_Description {
            get {
                return ResourceManager.GetString("EyesOfChaos_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faith boost.
        /// </summary>
        internal static string FaithBoost {
            get {
                return ResourceManager.GetString("FaithBoost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increases damage of a random ally based on Sage&apos;s Shield.
        /// </summary>
        internal static string FaithBoost_Description {
            get {
                return ResourceManager.GetString("FaithBoost_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal blow.
        /// </summary>
        internal static string FatalBlow {
            get {
                return ResourceManager.GetString("FatalBlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deals &lt;damage&gt; and burns &lt;resolve_damage&gt; to the farthest enemy. Then he pulls the enemy into the vanguard..
        /// </summary>
        internal static string FatalBlow_Description {
            get {
                return ResourceManager.GetString("FatalBlow_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Finger of Anubis.
        /// </summary>
        internal static string FingerOfAnubis {
            get {
                return ResourceManager.GetString("FingerOfAnubis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish a wounded.
        /// </summary>
        internal static string FinishWounded {
            get {
                return ResourceManager.GetString("FinishWounded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deals &lt;damage&gt; to the weakest enemy with the mark..
        /// </summary>
        internal static string FinishWounded_Description {
            get {
                return ResourceManager.GetString("FinishWounded_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flock Alpha Tactics.
        /// </summary>
        internal static string FlockAlphaTactics {
            get {
                return ResourceManager.GetString("FlockAlphaTactics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to He rushes to the vanguard. Deals &lt;damage&gt; to the strongest enemy and takes away &lt;resolve_damage&gt;..
        /// </summary>
        internal static string FlockAlphaTactics_Description {
            get {
                return ResourceManager.GetString("FlockAlphaTactics_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grim resolve.
        /// </summary>
        internal static string GrimResolve {
            get {
                return ResourceManager.GetString("GrimResolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deals &lt;damage&gt; and burns &lt;resolve_damage&gt; to the farthest enemy. Then he pulls the enemy into the vanguard..
        /// </summary>
        internal static string GrimResolve_Description {
            get {
                return ResourceManager.GetString("GrimResolve_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promise of a tomb guardian.
        /// </summary>
        internal static string GuardianPromise {
            get {
                return ResourceManager.GetString("GuardianPromise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increases its defense by &lt;defense&gt;. When auto-triggered, increases protection by &lt;defense_auto&gt;..
        /// </summary>
        internal static string GuardianPromise_Description {
            get {
                return ResourceManager.GetString("GuardianPromise_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardian woman.
        /// </summary>
        internal static string GuardianWoman {
            get {
                return ResourceManager.GetString("GuardianWoman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hand of Thousand Forms and Intentions.
        /// </summary>
        internal static string HandOfThousandForms {
            get {
                return ResourceManager.GetString("HandOfThousandForms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to vanguard and deal &lt;damage&gt; to the nearest enemy in lane. If the monk was already in the vanguard, then deal &lt;bonus_damage&gt;..
        /// </summary>
        internal static string HandOfThousandForms_Description {
            get {
                return ResourceManager.GetString("HandOfThousandForms_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haven&apos;t been punched in the face for a long time?.
        /// </summary>
        internal static string HaventBeenPunchedInTheFaceForALongTime_voice {
            get {
                return ResourceManager.GetString("HaventBeenPunchedInTheFaceForALongTime_voice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Healing salve.
        /// </summary>
        internal static string HealingSalve {
            get {
                return ResourceManager.GetString("HealingSalve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hear Me, Brothers!.
        /// </summary>
        internal static string HearMeBrothers {
            get {
                return ResourceManager.GetString("HearMeBrothers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to perform several feats so that other heroes will see this and join..
        /// </summary>
        internal static string HearMeBrothers_Description {
            get {
                return ResourceManager.GetString("HearMeBrothers_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rada The Old.
        /// </summary>
        internal static string Herbalist {
            get {
                return ResourceManager.GetString("Herbalist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wild herbs.
        /// </summary>
        internal static string HerbalistEquipment {
            get {
                return ResourceManager.GetString("HerbalistEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herb bag.
        /// </summary>
        internal static string HerbBag {
            get {
                return ResourceManager.GetString("HerbBag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string HerbBagDescription {
            get {
                return ResourceManager.GetString("HerbBagDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hermitage.
        /// </summary>
        internal static string Hermitage {
            get {
                return ResourceManager.GetString("Hermitage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden intention.
        /// </summary>
        internal static string HiddenIntention {
            get {
                return ResourceManager.GetString("HiddenIntention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deals &lt;damage&gt; to the weakest enemy. The monk himself moves to the rearguard..
        /// </summary>
        internal static string HiddenIntention_Description {
            get {
                return ResourceManager.GetString("HiddenIntention_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden thread.
        /// </summary>
        internal static string HiddenThread {
            get {
                return ResourceManager.GetString("HiddenThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hit from the shoulder.
        /// </summary>
        internal static string HitFromShoulder {
            get {
                return ResourceManager.GetString("HitFromShoulder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deals a powerful blow for &lt;damage&gt; and moves to the vanguard..
        /// </summary>
        internal static string HitFromShoulder_Description {
            get {
                return ResourceManager.GetString("HitFromShoulder_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leonidas.
        /// </summary>
        internal static string Hoplite {
            get {
                return ResourceManager.GetString("Hoplite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horned frog.
        /// </summary>
        internal static string HornedFrog {
            get {
                return ResourceManager.GetString("HornedFrog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HQ.
        /// </summary>
        internal static string Hq {
            get {
                return ResourceManager.GetString("Hq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Human Slayer.
        /// </summary>
        internal static string HumanSlayer {
            get {
                return ResourceManager.GetString("HumanSlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Hunt has begun!.
        /// </summary>
        internal static string Hunt {
            get {
                return ResourceManager.GetString("Hunt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Hunt_Description {
            get {
                return ResourceManager.GetString("Hunt_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore.
        /// </summary>
        internal static string Ignore_CrisisAftermath {
            get {
                return ResourceManager.GetString("Ignore_CrisisAftermath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inflict wrath on the entire group of heroes!
        ///- Everyone takes 1 damage penalty for 1 combat.
        ///- Berimir takes an additional 1 damage penalty for all combats until the end of the campaign..
        /// </summary>
        internal static string Ignore_CrisisAftermath_Hint {
            get {
                return ResourceManager.GetString("Ignore_CrisisAftermath_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Improved Damage.
        /// </summary>
        internal static string ImprovedAllDamage {
            get {
                return ResourceManager.GetString("ImprovedAllDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gain &lt;style=color1&gt;all&lt;/style&gt; damage on &lt;damage&gt;.
        /// </summary>
        internal static string ImprovedAllDamage_Description {
            get {
                return ResourceManager.GetString("ImprovedAllDamage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Improved armor.
        /// </summary>
        internal static string ImprovedArmor {
            get {
                return ResourceManager.GetString("ImprovedArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of the armor increased by 2 times..
        /// </summary>
        internal static string ImprovedArmorDescription {
            get {
                return ResourceManager.GetString("ImprovedArmorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Improved hit points.
        /// </summary>
        internal static string ImprovedHitPoints {
            get {
                return ResourceManager.GetString("ImprovedHitPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of the hit points increased by 2 times..
        /// </summary>
        internal static string ImprovedHitPointsDescription {
            get {
                return ResourceManager.GetString("ImprovedHitPointsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Improved Melee.
        /// </summary>
        internal static string ImprovedMeleeDamage {
            get {
                return ResourceManager.GetString("ImprovedMeleeDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gain &lt;style=color1&gt;melee&lt;/style&gt; damage on &lt;damage&gt;.
        /// </summary>
        internal static string ImprovedMeleeDamage_Description {
            get {
                return ResourceManager.GetString("ImprovedMeleeDamage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Improved Range.
        /// </summary>
        internal static string ImprovedRangeDamage {
            get {
                return ResourceManager.GetString("ImprovedRangeDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gain &lt;style=color1&gt;ranged&lt;/style&gt; damage on &lt;damage&gt;.
        /// </summary>
        internal static string ImprovedRangeDamage_Description {
            get {
                return ResourceManager.GetString("ImprovedRangeDamage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impulse.
        /// </summary>
        internal static string Impulse {
            get {
                return ResourceManager.GetString("Impulse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impulse generator.
        /// </summary>
        internal static string ImpulseGenerator {
            get {
                return ResourceManager.GetString("ImpulseGenerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string InfernalSickness_Crisis {
            get {
                return ResourceManager.GetString("InfernalSickness_Crisis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspirational breakthrough.
        /// </summary>
        internal static string InspirationalBreakthrough {
            get {
                return ResourceManager.GetString("InspirationalBreakthrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deals &lt;damage&gt; to the closest enemy in the line and inspires all allies in the rearguard, increasing their &lt;buff&gt; for &lt;duration&gt;..
        /// </summary>
        internal static string InspirationalBreakthrough_Description {
            get {
                return ResourceManager.GetString("InspirationalBreakthrough_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspiring rush.
        /// </summary>
        internal static string InspiringRush {
            get {
                return ResourceManager.GetString("InspiringRush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iron Stream.
        /// </summary>
        internal static string IronStream {
            get {
                return ResourceManager.GetString("IronStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deals &lt;damage&gt; to all enemies in line.
        /// </summary>
        internal static string IronStream_Description {
            get {
                return ResourceManager.GetString("IronStream_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start combats.
        /// </summary>
        internal static string JobTypeCombats {
            get {
                return ResourceManager.GetString("JobTypeCombats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete campaigns.
        /// </summary>
        internal static string JobTypeCompleteCampans {
            get {
                return ResourceManager.GetString("JobTypeCompleteCampans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defeat enemies.
        /// </summary>
        internal static string JobTypeDefeat {
            get {
                return ResourceManager.GetString("JobTypeDefeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Juggernaut heavy power armor.
        /// </summary>
        internal static string JuggernautHeavyPowerArmor {
            get {
                return ResourceManager.GetString("JuggernautHeavyPowerArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just hit a whild boar with the knife.
        /// </summary>
        internal static string JustHitBoarWithKnife {
            get {
                return ResourceManager.GetString("JustHitBoarWithKnife", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deals 1 damage to the closest enemy in the line. If it was the strongest enemy, it applies bleeding for 2 rounds, dealing damage to 1 health each round..
        /// </summary>
        internal static string JustHitBoarWithKnife_Description {
            get {
                return ResourceManager.GetString("JustHitBoarWithKnife_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Last Breath.
        /// </summary>
        internal static string LastBreath {
            get {
                return ResourceManager.GetString("LastBreath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore &lt;hp_restore&gt; if hit points below &lt;hp_threshold&gt;.
        /// </summary>
        internal static string LastBreath_Description {
            get {
                return ResourceManager.GetString("LastBreath_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last chance to peace.
        /// </summary>
        internal static string LastChanceToPeace {
            get {
                return ResourceManager.GetString("LastChanceToPeace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string LastChanceToPeace_Description {
            get {
                return ResourceManager.GetString("LastChanceToPeace_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Look out!.
        /// </summary>
        internal static string LookOut {
            get {
                return ResourceManager.GetString("LookOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increases the Defense of the nearest ally in a column by &lt;defence&gt; until the end of the ally&apos;s turn. The swordsman himself moves to the vanguard. When automatically triggered, increases your defense by &lt;auto_defence&gt;..
        /// </summary>
        internal static string LookOut_Description {
            get {
                return ResourceManager.GetString("LookOut_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lord Of Non Human Realm.
        /// </summary>
        internal static string LordOfNonHumanRealm {
            get {
                return ResourceManager.GetString("LordOfNonHumanRealm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Madness within eyes.
        /// </summary>
        internal static string MadnessWithinEyes {
            get {
                return ResourceManager.GetString("MadnessWithinEyes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MadnessWithinEyes_Description {
            get {
                return ResourceManager.GetString("MadnessWithinEyes_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marauder.
        /// </summary>
        internal static string Marauder {
            get {
                return ResourceManager.GetString("Marauder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mass heal.
        /// </summary>
        internal static string MassHeal {
            get {
                return ResourceManager.GetString("MassHeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masterful staff hit.
        /// </summary>
        internal static string MasterfulStaffHit {
            get {
                return ResourceManager.GetString("MasterfulStaffHit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MasterfulStaffHit_Description {
            get {
                return ResourceManager.GetString("MasterfulStaffHit_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gelik.
        /// </summary>
        internal static string Medjay {
            get {
                return ResourceManager.GetString("Medjay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melee.
        /// </summary>
        internal static string Melee {
            get {
                return ResourceManager.GetString("Melee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Mines.
        /// </summary>
        internal static string Mines {
            get {
                return ResourceManager.GetString("Mines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mk2 medium power armor.
        /// </summary>
        internal static string Mk2MediumPowerArmor {
            get {
                return ResourceManager.GetString("Mk2MediumPowerArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Mk2MediumPowerArmorDescription {
            get {
                return ResourceManager.GetString("Mk2MediumPowerArmorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monastery in the flames.
        /// </summary>
        internal static string Monastery {
            get {
                return ResourceManager.GetString("Monastery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maosin.
        /// </summary>
        internal static string Monk {
            get {
                return ResourceManager.GetString("Monk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nano-metal long cloths.
        /// </summary>
        internal static string NanoMetalLongCloths {
            get {
                return ResourceManager.GetString("NanoMetalLongCloths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ninth trigram.
        /// </summary>
        internal static string NinthTrigram {
            get {
                return ResourceManager.GetString("NinthTrigram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NinthTrigram_Description {
            get {
                return ResourceManager.GetString("NinthTrigram_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Violence, Please....
        /// </summary>
        internal static string NoViolencePlease {
            get {
                return ResourceManager.GetString("NoViolencePlease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NoViolencePlease_Description {
            get {
                return ResourceManager.GetString("NoViolencePlease_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obey.
        /// </summary>
        internal static string Obey_CrisisAftermath {
            get {
                return ResourceManager.GetString("Obey_CrisisAftermath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Obey_CrisisAftermath_Hint {
            get {
                return ResourceManager.GetString("Obey_CrisisAftermath_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obey all.
        /// </summary>
        internal static string ObeyAll_CrisisAftermath {
            get {
                return ResourceManager.GetString("ObeyAll_CrisisAftermath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old good brawl.
        /// </summary>
        internal static string OldGoodBrawl {
            get {
                return ResourceManager.GetString("OldGoodBrawl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moves to the vanguard and deals 2 damage. Does not waste energy if the same move was previously used..
        /// </summary>
        internal static string OldGoodBrawl_Description {
            get {
                return ResourceManager.GetString("OldGoodBrawl_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oldman.
        /// </summary>
        internal static string Oldman {
            get {
                return ResourceManager.GetString("Oldman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ominous Thorn.
        /// </summary>
        internal static string OminousThorn {
            get {
                return ResourceManager.GetString("OminousThorn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strongly attacks the closest enemy in line with &lt;damage&gt;..
        /// </summary>
        internal static string OminousThorn_Description {
            get {
                return ResourceManager.GetString("OminousThorn_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paralitic Chor.
        /// </summary>
        internal static string ParaliticChor {
            get {
                return ResourceManager.GetString("ParaliticChor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deaf.
        /// </summary>
        internal static string Partisan {
            get {
                return ResourceManager.GetString("Partisan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partisan.
        /// </summary>
        internal static string Partisan_Hidden {
            get {
                return ResourceManager.GetString("Partisan_Hidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Pit.
        /// </summary>
        internal static string Pit {
            get {
                return ResourceManager.GetString("Pit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay attention.
        /// </summary>
        internal static string Prey_CrisisAftermath {
            get {
                return ResourceManager.GetString("Prey_CrisisAftermath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of the heroes feels the haunting presence of the his faith ancient ones. They demand his attention. They demand his help. Such requests cannot be ignored. Especially in the dark future, where only ancient forces make heroes..
        /// </summary>
        internal static string Preying_Crisis {
            get {
                return ResourceManager.GetString("Preying_Crisis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranged.
        /// </summary>
        internal static string Ranged {
            get {
                return ResourceManager.GetString("Ranged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapid shot.
        /// </summary>
        internal static string RapidShot {
            get {
                return ResourceManager.GetString("RapidShot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rearguard Extra HP.
        /// </summary>
        internal static string RearguardExtraHitPoints {
            get {
                return ResourceManager.GetString("RearguardExtraHitPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra &lt;hp&gt; to ally &lt;style=color1&gt;rearguard&lt;/style&gt;.
        /// </summary>
        internal static string RearguardExtraHitPoints_Description {
            get {
                return ResourceManager.GetString("RearguardExtraHitPoints_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rearguard Extra SP.
        /// </summary>
        internal static string RearguardExtraShieldPoints {
            get {
                return ResourceManager.GetString("RearguardExtraShieldPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra &lt;sp&gt; to ally &lt;style=color1&gt;rearguard&lt;/style&gt;.
        /// </summary>
        internal static string RearguardExtraShieldPoints_Description {
            get {
                return ResourceManager.GetString("RearguardExtraShieldPoints_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduce Rearguard HP.
        /// </summary>
        internal static string RearguardReduceHitPoints {
            get {
                return ResourceManager.GetString("RearguardReduceHitPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduce &lt;hp&gt; of enemy &lt;style=color1&gt;rearguard&lt;/style&gt;.
        /// </summary>
        internal static string RearguardReduceHitPoints_Description {
            get {
                return ResourceManager.GetString("RearguardReduceHitPoints_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduce &lt;resolve&gt; of enemy &lt;style=color1&gt;rearguard&lt;/style&gt;.
        /// </summary>
        internal static string RearguardReduceResolve_Description {
            get {
                return ResourceManager.GetString("RearguardReduceResolve_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduce Rearguard SP.
        /// </summary>
        internal static string RearguardReduceShieldPoints {
            get {
                return ResourceManager.GetString("RearguardReduceShieldPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduce &lt;sp&gt; of enemy &lt;style=color1&gt;rearguard&lt;/style&gt;.
        /// </summary>
        internal static string RearguardReduceShieldPoints_Description {
            get {
                return ResourceManager.GetString("RearguardReduceShieldPoints_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff of Redemption.
        /// </summary>
        internal static string RedemptionStaff {
            get {
                return ResourceManager.GetString("RedemptionStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduce resolve.
        /// </summary>
        internal static string ReduceEnemyResolvePoints {
            get {
                return ResourceManager.GetString("ReduceEnemyResolvePoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduce SP.
        /// </summary>
        internal static string ReduceEnemyShieldPoints {
            get {
                return ResourceManager.GetString("ReduceEnemyShieldPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regenerative protocol.
        /// </summary>
        internal static string RegenerativeProtocol {
            get {
                return ResourceManager.GetString("RegenerativeProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restores &lt;hp&gt; and goes to the rearguard..
        /// </summary>
        internal static string RegenerativeProtocol_Description {
            get {
                return ResourceManager.GetString("RegenerativeProtocol_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reproach.
        /// </summary>
        internal static string Reproach {
            get {
                return ResourceManager.GetString("Reproach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Reproach_Description {
            get {
                return ResourceManager.GetString("Reproach_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rest.
        /// </summary>
        internal static string Rest_CrisisAftermath {
            get {
                return ResourceManager.GetString("Rest_CrisisAftermath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rest all.
        /// </summary>
        internal static string RestAll_CrisisAftermath {
            get {
                return ResourceManager.GetString("RestAll_CrisisAftermath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string RestAll_CrisisAftermath_Hint {
            get {
                return ResourceManager.GetString("RestAll_CrisisAftermath_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revenge Of Wild Eye.
        /// </summary>
        internal static string RevengeOfWildEye {
            get {
                return ResourceManager.GetString("RevengeOfWildEye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rise your swords!.
        /// </summary>
        internal static string RiseYourSwords {
            get {
                return ResourceManager.GetString("RiseYourSwords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increases the damage of melee attack moves by &lt;damage_buff&gt; for all allies for &lt;duration&gt;..
        /// </summary>
        internal static string RiseYourSwords_Description {
            get {
                return ResourceManager.GetString("RiseYourSwords_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hawk.
        /// </summary>
        internal static string Robber {
            get {
                return ResourceManager.GetString("Robber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robber.
        /// </summary>
        internal static string Robber_Hidden {
            get {
                return ResourceManager.GetString("Robber_Hidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sabotage.
        /// </summary>
        internal static string Sabotage {
            get {
                return ResourceManager.GetString("Sabotage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deals 3 damage to the weakest enemy. The partisan himself moves to the rearguard..
        /// </summary>
        internal static string Sabotage_Description {
            get {
                return ResourceManager.GetString("Sabotage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scarabeus King&apos;s Leg.
        /// </summary>
        internal static string ScarabeusKingLeg {
            get {
                return ResourceManager.GetString("ScarabeusKingLeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serpent trap.
        /// </summary>
        internal static string SerpentTrap {
            get {
                return ResourceManager.GetString("SerpentTrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moves forward and deals &lt;damage&gt; damage to the strongest enemy..
        /// </summary>
        internal static string SerpentTrap_Description {
            get {
                return ResourceManager.GetString("SerpentTrap_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship Graveyard.
        /// </summary>
        internal static string ShipGraveyard {
            get {
                return ResourceManager.GetString("ShipGraveyard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silver wind necklace.
        /// </summary>
        internal static string SilverWindNecklace {
            get {
                return ResourceManager.GetString("SilverWindNecklace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SilverWindNecklaceDescription {
            get {
                return ResourceManager.GetString("SilverWindNecklaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snow.
        /// </summary>
        internal static string snow_prop {
            get {
                return ResourceManager.GetString("snow_prop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ping.
        /// </summary>
        internal static string Spearman {
            get {
                return ResourceManager.GetString("Spearman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spiral Inversion.
        /// </summary>
        internal static string SpiralInversion {
            get {
                return ResourceManager.GetString("SpiralInversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SpiralInversion_Description {
            get {
                return ResourceManager.GetString("SpiralInversion_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff hits.
        /// </summary>
        internal static string StaffHit {
            get {
                return ResourceManager.GetString("StaffHit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Starvation_Crisis {
            get {
                return ResourceManager.GetString("Starvation_Crisis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string StarveAll_CrisisAftermath {
            get {
                return ResourceManager.GetString("StarveAll_CrisisAftermath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string StarveAll_CrisisAftermath_Hint {
            get {
                return ResourceManager.GetString("StarveAll_CrisisAftermath_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string StarveSolo_CrisisAftermath {
            get {
                return ResourceManager.GetString("StarveSolo_CrisisAftermath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string StarveSolo_CrisisAftermath_Hint {
            get {
                return ResourceManager.GetString("StarveSolo_CrisisAftermath_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stay strong!.
        /// </summary>
        internal static string StayStrong {
            get {
                return ResourceManager.GetString("StayStrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increases your defense by &lt;defence&gt; until the end of the round. When auto-triggered, it increases its defense by &lt;auto_defence&gt; until the next turn..
        /// </summary>
        internal static string StayStrong_Description {
            get {
                return ResourceManager.GetString("StayStrong_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stryga.
        /// </summary>
        internal static string Stryga {
            get {
                return ResourceManager.GetString("Stryga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppressive fire.
        /// </summary>
        internal static string SuppressiveFire {
            get {
                return ResourceManager.GetString("SuppressiveFire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surprise maneuver.
        /// </summary>
        internal static string SurpriseManeuver {
            get {
                return ResourceManager.GetString("SurpriseManeuver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swaps with the strongest ally in the neighborhood. The maneuver gives 2 defenses to the partisan and the ally..
        /// </summary>
        internal static string SurpriseManeuver_Description {
            get {
                return ResourceManager.GetString("SurpriseManeuver_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Svarog&apos;s Blast Furnace.
        /// </summary>
        internal static string SvarogBlastFurnace {
            get {
                return ResourceManager.GetString("SvarogBlastFurnace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evil swamp.
        /// </summary>
        internal static string Swamp {
            get {
                return ResourceManager.GetString("Swamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Berimir.
        /// </summary>
        internal static string Swordsman {
            get {
                return ResourceManager.GetString("Swordsman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol of the God.
        /// </summary>
        internal static string SymbolOfGod {
            get {
                return ResourceManager.GetString("SymbolOfGod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nafrit.
        /// </summary>
        internal static string Synth {
            get {
                return ResourceManager.GetString("Synth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Lower Caste Synth.
        /// </summary>
        internal static string Synth_Hidden {
            get {
                return ResourceManager.GetString("Synth_Hidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tactical maneuver.
        /// </summary>
        internal static string TacticalManeuver {
            get {
                return ResourceManager.GetString("TacticalManeuver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The good weather today....
        /// </summary>
        internal static string TheGoodWeather_voice {
            get {
                return ResourceManager.GetString("TheGoodWeather_voice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Thicket.
        /// </summary>
        internal static string Thicket {
            get {
                return ResourceManager.GetString("Thicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toxic gas bomb.
        /// </summary>
        internal static string ToxicGasBomb {
            get {
                return ResourceManager.GetString("ToxicGasBomb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracker&apos;s savvy.
        /// </summary>
        internal static string TrackerSavvy {
            get {
                return ResourceManager.GetString("TrackerSavvy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TrackerSavvy_Description {
            get {
                return ResourceManager.GetString("TrackerSavvy_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two plus two is five....
        /// </summary>
        internal static string TwoPlusTwoIsFive_voice {
            get {
                return ResourceManager.GetString("TwoPlusTwoIsFive_voice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vampire bite.
        /// </summary>
        internal static string VampireBite {
            get {
                return ResourceManager.GetString("VampireBite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vanguard Extra HP.
        /// </summary>
        internal static string VanguardExtraHitPoints {
            get {
                return ResourceManager.GetString("VanguardExtraHitPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra &lt;hp&gt; to ally &lt;style=color1&gt;vanguard&lt;/style&gt;.
        /// </summary>
        internal static string VanguardExtraHitPoints_Description {
            get {
                return ResourceManager.GetString("VanguardExtraHitPoints_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vanguard Extra SP.
        /// </summary>
        internal static string VanguardExtraShieldPoints {
            get {
                return ResourceManager.GetString("VanguardExtraShieldPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra &lt;sp&gt; to ally &lt;style=color1&gt;vanguard&lt;/style&gt;.
        /// </summary>
        internal static string VanguardExtraShieldPoints_Description {
            get {
                return ResourceManager.GetString("VanguardExtraShieldPoints_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduce Vanguard HP.
        /// </summary>
        internal static string VanguardReduceHitPoints {
            get {
                return ResourceManager.GetString("VanguardReduceHitPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduce &lt;hp&gt; of enemy &lt;style=color1&gt;vanguard&lt;/style&gt;.
        /// </summary>
        internal static string VanguardReduceHitPoints_Description {
            get {
                return ResourceManager.GetString("VanguardReduceHitPoints_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduce &lt;resolve&gt; of enemy &lt;style=color1&gt;vanguard&lt;/style&gt;.
        /// </summary>
        internal static string VanguardReduceResolve_Description {
            get {
                return ResourceManager.GetString("VanguardReduceResolve_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduce Vanguard SP.
        /// </summary>
        internal static string VanguardReduceShieldPoints {
            get {
                return ResourceManager.GetString("VanguardReduceShieldPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduce &lt;sp&gt; of enemy &lt;style=color1&gt;vanguard&lt;/style&gt;.
        /// </summary>
        internal static string VanguardReduceShieldPoints_Description {
            get {
                return ResourceManager.GetString("VanguardReduceShieldPoints_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veles protection.
        /// </summary>
        internal static string VelesProtection {
            get {
                return ResourceManager.GetString("VelesProtection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On &lt;turns_duration&gt; increases shields by &lt;sp&gt; and moves to the rearguard..
        /// </summary>
        internal static string VelesProtection_Description {
            get {
                return ResourceManager.GetString("VelesProtection_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volkolak.
        /// </summary>
        internal static string Volkolak {
            get {
                return ResourceManager.GetString("Volkolak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volkolak claws.
        /// </summary>
        internal static string VolkolakClaws {
            get {
                return ResourceManager.GetString("VolkolakClaws", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warrior of the Wolf Time.
        /// </summary>
        internal static string VolkolakWarrior {
            get {
                return ResourceManager.GetString("VolkolakWarrior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sword pieces.
        /// </summary>
        internal static string WarriorEquipment {
            get {
                return ResourceManager.GetString("WarriorEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We Live Only Once!.
        /// </summary>
        internal static string WeOnlyLiveOnce {
            get {
                return ResourceManager.GetString("WeOnlyLiveOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deals &lt;damage&gt; to the closest enemy in the line. If it was the strongest enemy, it applies bleeding for &lt;duration&gt;, dealing &lt;bleed_damage&gt; each round..
        /// </summary>
        internal static string WeOnlyLiveOnce_Description {
            get {
                return ResourceManager.GetString("WeOnlyLiveOnce_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wide sword slash.
        /// </summary>
        internal static string WideSwordSlash {
            get {
                return ResourceManager.GetString("WideSwordSlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win campaigns.
        /// </summary>
        internal static string WinCampaigns {
            get {
                return ResourceManager.GetString("WinCampaigns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind wheel.
        /// </summary>
        internal static string WindWheel {
            get {
                return ResourceManager.GetString("WindWheel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deals 4 damage to the strongest enemy. And misses the next move..
        /// </summary>
        internal static string WindWheel_Description {
            get {
                return ResourceManager.GetString("WindWheel_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wings Of Veles.
        /// </summary>
        internal static string WingsOfVeles {
            get {
                return ResourceManager.GetString("WingsOfVeles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increases the damage of any attacking moves by 1. And reduces the cost of all attacking skills by 1 energy..
        /// </summary>
        internal static string WingsOfVeles_Description {
            get {
                return ResourceManager.GetString("WingsOfVeles_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will-o-Wisp.
        /// </summary>
        internal static string Wisp {
            get {
                return ResourceManager.GetString("Wisp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Woman short.
        /// </summary>
        internal static string WomanShort {
            get {
                return ResourceManager.GetString("WomanShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string WomanShortDescription {
            get {
                return ResourceManager.GetString("WomanShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wooden hand sculpture.
        /// </summary>
        internal static string WoodenHandSculpture {
            get {
                return ResourceManager.GetString("WoodenHandSculpture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string WoodenHandSculptureDescription {
            get {
                return ResourceManager.GetString("WoodenHandSculptureDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zduhach Might.
        /// </summary>
        internal static string ZduhachMight {
            get {
                return ResourceManager.GetString("ZduhachMight", resourceCulture);
            }
        }
    }
}
