//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UiResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UiResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Client.UiResource", typeof(UiResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  !&quot;#$%&amp;\&apos;()*+,-./0123456789:;&lt;=&gt;?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~.
        /// </summary>
        internal static string _AllChars {
            get {
                return ResourceManager.GetString("_AllChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept challenge.
        /// </summary>
        internal static string AcceptChallengeButtonTitle {
            get {
                return ResourceManager.GetString("AcceptChallengeButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjutant.
        /// </summary>
        internal static string AdjutantButtonTitle {
            get {
                return ResourceManager.GetString("AdjutantButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armor: {0}.
        /// </summary>
        internal static string ArmorLabelTemplate {
            get {
                return ResourceManager.GetString("ArmorLabelTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armory.
        /// </summary>
        internal static string ArmoryButtonTitle {
            get {
                return ResourceManager.GetString("ArmoryButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-combat.
        /// </summary>
        internal static string AutocombatButtonTitle {
            get {
                return ResourceManager.GetString("AutocombatButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maneuvers available.
        /// </summary>
        internal static string AvailableManeuversIndicatorTemplate {
            get {
                return ResourceManager.GetString("AvailableManeuversIndicatorTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string BackButtonTitle {
            get {
                return ResourceManager.GetString("BackButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to the map.
        /// </summary>
        internal static string BackToMapMenuButtonTitle {
            get {
                return ResourceManager.GetString("BackToMapMenuButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barraks.
        /// </summary>
        internal static string BarraksButtonTitle {
            get {
                return ResourceManager.GetString("BarraksButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestiary.
        /// </summary>
        internal static string BestiaryButtonTitle {
            get {
                return ResourceManager.GetString("BestiaryButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lvl.
        /// </summary>
        internal static string BiomeLevelText {
            get {
                return ResourceManager.GetString("BiomeLevelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reward.
        /// </summary>
        internal static string CampaignRewardsLabelText {
            get {
                return ResourceManager.GetString("CampaignRewardsLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to START.
        /// </summary>
        internal static string CampaignSelectButtonTitle {
            get {
                return ResourceManager.GetString("CampaignSelectButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - done.
        /// </summary>
        internal static string CampaignsJobCompletePatternSid {
            get {
                return ResourceManager.GetString("CampaignsJobCompletePatternSid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1}/{2}.
        /// </summary>
        internal static string CampaignsJobProgressPatternSid {
            get {
                return ResourceManager.GetString("CampaignsJobProgressPatternSid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete any campaigns.
        /// </summary>
        internal static string CampaignsJobTitleSid {
            get {
                return ResourceManager.GetString("CampaignsJobTitleSid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenge.
        /// </summary>
        internal static string CampaignStageDisplayNameChallenge {
            get {
                return ResourceManager.GetString("CampaignStageDisplayNameChallenge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combat.
        /// </summary>
        internal static string CampaignStageDisplayNameCombat {
            get {
                return ResourceManager.GetString("CampaignStageDisplayNameCombat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crisis.
        /// </summary>
        internal static string CampaignStageDisplayNameCrisis {
            get {
                return ResourceManager.GetString("CampaignStageDisplayNameCrisis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish campaign.
        /// </summary>
        internal static string CampaignStageDisplayNameFinish {
            get {
                return ResourceManager.GetString("CampaignStageDisplayNameFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rest.
        /// </summary>
        internal static string CampaignStageDisplayNameRest {
            get {
                return ResourceManager.GetString("CampaignStageDisplayNameRest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some event.
        /// </summary>
        internal static string CampaignStageDisplayNameTextEvent {
            get {
                return ResourceManager.GetString("CampaignStageDisplayNameTextEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ???.
        /// </summary>
        internal static string CampaignStageDisplayNameUnknown {
            get {
                return ResourceManager.GetString("CampaignStageDisplayNameUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage {0}.
        /// </summary>
        internal static string CampaignStageTitle {
            get {
                return ResourceManager.GetString("CampaignStageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chronicles.
        /// </summary>
        internal static string ChroniclesButtonTitle {
            get {
                return ResourceManager.GetString("ChroniclesButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string CloseButtonTitle {
            get {
                return ResourceManager.GetString("CloseButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string CombatIndicatorNegativeHpTemplate {
            get {
                return ResourceManager.GetString("CombatIndicatorNegativeHpTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;{0}&gt;.
        /// </summary>
        internal static string CombatIndicatorNegativeSpTemplate {
            get {
                return ResourceManager.GetString("CombatIndicatorNegativeSpTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +{0}.
        /// </summary>
        internal static string CombatIndicatorPositiveHpTemplate {
            get {
                return ResourceManager.GetString("CombatIndicatorPositiveHpTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +&lt;{0}&gt;.
        /// </summary>
        internal static string CombatIndicatorPositiveSpTemplate {
            get {
                return ResourceManager.GetString("CombatIndicatorPositiveSpTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combat length:.
        /// </summary>
        internal static string CombatLengthLabel {
            get {
                return ResourceManager.GetString("CombatLengthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combat level: {0}.
        /// </summary>
        internal static string CombatLevelTemplate {
            get {
                return ResourceManager.GetString("CombatLevelTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} xp to level up.
        /// </summary>
        internal static string CombatLevelUpTemplate {
            get {
                return ResourceManager.GetString("CombatLevelUpTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combat progress: {0}/{1}.
        /// </summary>
        internal static string CombatProgressTemplate {
            get {
                return ResourceManager.GetString("CombatProgressTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defeat!.
        /// </summary>
        internal static string CombatResultDefeatText {
            get {
                return ResourceManager.GetString("CombatResultDefeatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items found:.
        /// </summary>
        internal static string CombatResultItemsFoundLabel {
            get {
                return ResourceManager.GetString("CombatResultItemsFoundLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monster danger decreased to {0} (on -50%).
        /// </summary>
        internal static string CombatResultMonsterDangerDecreasedTemplate {
            get {
                return ResourceManager.GetString("CombatResultMonsterDangerDecreasedTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monster danger increased to {0}.
        /// </summary>
        internal static string CombatResultMonsterDangerIncreasedTemplate {
            get {
                return ResourceManager.GetString("CombatResultMonsterDangerIncreasedTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next combat....
        /// </summary>
        internal static string CombatResultNextText {
            get {
                return ResourceManager.GetString("CombatResultNextText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Victory!.
        /// </summary>
        internal static string CombatResultVictoryText {
            get {
                return ResourceManager.GetString("CombatResultVictoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CombatTutorialText {
            get {
                return ResourceManager.GetString("CombatTutorialText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to command center.
        /// </summary>
        internal static string CompleteCampaignButtonTitle {
            get {
                return ResourceManager.GetString("CompleteCampaignButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete the game.
        /// </summary>
        internal static string CompleteGameButtonTitle {
            get {
                return ResourceManager.GetString("CompleteGameButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string ConfirmButtonTitle {
            get {
                return ResourceManager.GetString("ConfirmButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you perform this attack from the current position, then none of the opponents will be harmed.
        ///The attack will be ineffective.
        ///Perhaps you should first choose a better position for the hero or choose another action.
        ///Do you really need to spend the priceless current move for nothing?.
        /// </summary>
        internal static string ConfirmIneffectiveAttackText {
            get {
                return ResourceManager.GetString("ConfirmIneffectiveAttackText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits.
        /// </summary>
        internal static string CreditsButtonTitle {
            get {
                return ResourceManager.GetString("CreditsButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quests.
        /// </summary>
        internal static string CurrentQuestButtonTitle {
            get {
                return ResourceManager.GetString("CurrentQuestButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage: {0} - {1} to {2}.
        /// </summary>
        internal static string DamageEffectRuleText {
            get {
                return ResourceManager.GetString("DamageEffectRuleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage: {0}.
        /// </summary>
        internal static string DamageLabelTemplate {
            get {
                return ResourceManager.GetString("DamageLabelTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease hitpoints on {0}% of {2} on {1} turns.
        /// </summary>
        internal static string DecreaseHitPointsPercentEffectRuleText {
            get {
                return ResourceManager.GetString("DecreaseHitPointsPercentEffectRuleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease shields on {0}% of {2} on {1} turns.
        /// </summary>
        internal static string DecreaseShieldsPercentEffectRuleText {
            get {
                return ResourceManager.GetString("DecreaseShieldsPercentEffectRuleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease damage on {0} of {2} on {1} turns.
        /// </summary>
        internal static string DecreseDamageEffectRuleText {
            get {
                return ResourceManager.GetString("DecreseDamageEffectRuleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease damage on {0}% of {2} on {1} turns.
        /// </summary>
        internal static string DecreseDamagePercentEffectRuleText {
            get {
                return ResourceManager.GetString("DecreseDamagePercentEffectRuleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - done.
        /// </summary>
        internal static string DefeatsJobCompletePatternSid {
            get {
                return ResourceManager.GetString("DefeatsJobCompletePatternSid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1}/{2}.
        /// </summary>
        internal static string DefeatsJobProgressPatternSid {
            get {
                return ResourceManager.GetString("DefeatsJobProgressPatternSid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defeats.
        /// </summary>
        internal static string DefeatsJobTitleSid {
            get {
                return ResourceManager.GetString("DefeatsJobTitleSid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demo.
        /// </summary>
        internal static string DemoMarkerText {
            get {
                return ResourceManager.GetString("DemoMarkerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press [SPACE] to continue.
        /// </summary>
        internal static string DialogueContinueText {
            get {
                return ResourceManager.GetString("DialogueContinueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if right ally with shield.
        /// </summary>
        internal static string EffectConditionIsRightAllyWithShieldText {
            get {
                return ResourceManager.GetString("EffectConditionIsRightAllyWithShieldText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is end of the game. Congratulations!{0}Thank you for attention.
        /// </summary>
        internal static string EndOfGameMessage {
            get {
                return ResourceManager.GetString("EndOfGameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} x {1} to upgrade.
        /// </summary>
        internal static string EquipmentResourceRequipmentTemplate {
            get {
                return ResourceManager.GetString("EquipmentResourceRequipmentTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1} lvl).
        /// </summary>
        internal static string EquipmentTitleTemplate {
            get {
                return ResourceManager.GetString("EquipmentTitleTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade is available!.
        /// </summary>
        internal static string EquipmentUpgradeMarkerText {
            get {
                return ResourceManager.GetString("EquipmentUpgradeMarkerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string EventTutorialText {
            get {
                return ResourceManager.GetString("EventTutorialText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit game.
        /// </summary>
        internal static string ExitGameButtonTitle {
            get {
                return ResourceManager.GetString("ExitGameButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avangard.
        /// </summary>
        internal static string FieldManeuversVisualizer_Draw_Avanguard {
            get {
                return ResourceManager.GetString("FieldManeuversVisualizer_Draw_Avanguard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rearguard.
        /// </summary>
        internal static string FieldManeuversVisualizer_Draw_Rearguard {
            get {
                return ResourceManager.GetString("FieldManeuversVisualizer_Draw_Rearguard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formation.
        /// </summary>
        internal static string FormationButtonTitle {
            get {
                return ResourceManager.GetString("FormationButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} combats left.
        /// </summary>
        internal static string GlobalEffectDurationTemplate {
            get {
                return ResourceManager.GetString("GlobalEffectDurationTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heal: {0} - {1} to {2}.
        /// </summary>
        internal static string HealEffectRuleText {
            get {
                return ResourceManager.GetString("HealEffectRuleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment.
        /// </summary>
        internal static string HeroEquipmentInfoTitle {
            get {
                return ResourceManager.GetString("HeroEquipmentInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Info.
        /// </summary>
        internal static string HeroGeneralInfoTitle {
            get {
                return ResourceManager.GetString("HeroGeneralInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perks.
        /// </summary>
        internal static string HeroPerkInfoTitle {
            get {
                return ResourceManager.GetString("HeroPerkInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills.
        /// </summary>
        internal static string HeroSkillsInfoTitle {
            get {
                return ResourceManager.GetString("HeroSkillsInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hit points: {0}.
        /// </summary>
        internal static string HitPointsLabelTemplate {
            get {
                return ResourceManager.GetString("HitPointsLabelTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase damage on {0} of {2} on {1} turns.
        /// </summary>
        internal static string IncreaseDamageEffectRuleText {
            get {
                return ResourceManager.GetString("IncreaseDamageEffectRuleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase damage on {0}% of {2} on {1} turns.
        /// </summary>
        internal static string IncreaseDamagePercentEffectRuleText {
            get {
                return ResourceManager.GetString("IncreaseDamagePercentEffectRuleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase hit points on {0}% of {2} on {1} turns.
        /// </summary>
        internal static string IncreaseHitPointsPercentEffectRuleText {
            get {
                return ResourceManager.GetString("IncreaseHitPointsPercentEffectRuleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase shields on {0}% of {2} on {1} turns.
        /// </summary>
        internal static string IncreaseShieldsPercentEffectRuleText {
            get {
                return ResourceManager.GetString("IncreaseShieldsPercentEffectRuleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block!.
        /// </summary>
        internal static string IndicatorBlockAnyDamage {
            get {
                return ResourceManager.GetString("IndicatorBlockAnyDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evasion!.
        /// </summary>
        internal static string IndicatorEvasion {
            get {
                return ResourceManager.GetString("IndicatorEvasion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip!.
        /// </summary>
        internal static string IndicatorSkipTurn {
            get {
                return ResourceManager.GetString("IndicatorSkipTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0123456789.
        /// </summary>
        internal static string IndicatorWarmupText {
            get {
                return ResourceManager.GetString("IndicatorWarmupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string InfoButtonTitle {
            get {
                return ResourceManager.GetString("InfoButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory.
        /// </summary>
        internal static string InventoryButtonTitle {
            get {
                return ResourceManager.GetString("InventoryButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start combats.
        /// </summary>
        internal static string JobTypeCombats {
            get {
                return ResourceManager.GetString("JobTypeCombats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete campaigns.
        /// </summary>
        internal static string JobTypeCompleteCampans {
            get {
                return ResourceManager.GetString("JobTypeCompleteCampans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defeat enemies.
        /// </summary>
        internal static string JobTypeDefeat {
            get {
                return ResourceManager.GetString("JobTypeDefeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level Up.
        /// </summary>
        internal static string LevelUpButtonTitle {
            get {
                return ResourceManager.GetString("LevelUpButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw {0} - {1} hp from {2}.
        /// </summary>
        internal static string LifeDrawEffectRuleText {
            get {
                return ResourceManager.GetString("LifeDrawEffectRuleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long.
        /// </summary>
        internal static string LongCombatSequenceText {
            get {
                return ResourceManager.GetString("LongCombatSequenceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Psy-energy cost: {0}.
        /// </summary>
        internal static string ManaCostLabelTemplate {
            get {
                return ResourceManager.GetString("ManaCostLabelTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Psy-energy: {0}/{1}.
        /// </summary>
        internal static string ManaLabelTemplate {
            get {
                return ResourceManager.GetString("ManaLabelTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MapTutorialText {
            get {
                return ResourceManager.GetString("MapTutorialText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        internal static string MediumCombatSequenceText {
            get {
                return ResourceManager.GetString("MediumCombatSequenceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Victory!.
        /// </summary>
        internal static string MiniGame_Victory {
            get {
                return ResourceManager.GetString("MiniGame_Victory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danger of the monsters: {0}.
        /// </summary>
        internal static string MonsterDangerTemplate {
            get {
                return ResourceManager.GetString("MonsterDangerTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lvl.
        /// </summary>
        internal static string MonsterLevelShortText {
            get {
                return ResourceManager.GetString("MonsterLevelShortText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to the pool.
        /// </summary>
        internal static string MoveToThePoolButtonTitle {
            get {
                return ResourceManager.GetString("MoveToThePoolButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party.
        /// </summary>
        internal static string PartyButtonTitle {
            get {
                return ResourceManager.GetString("PartyButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage: {0} - {1} to {2} during {3} turns.
        /// </summary>
        internal static string PeriodicDamageEffectRuleText {
            get {
                return ResourceManager.GetString("PeriodicDamageEffectRuleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heal over time: {0} - {1} during {3} to {2}.
        /// </summary>
        internal static string PeriodicHealEffectRuleText {
            get {
                return ResourceManager.GetString("PeriodicHealEffectRuleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Combat.
        /// </summary>
        internal static string PlayFreeCombatButtonTitle {
            get {
                return ResourceManager.GetString("PlayFreeCombatButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Story.
        /// </summary>
        internal static string PlayStoryButtonTitle {
            get {
                return ResourceManager.GetString("PlayStoryButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduce incoming damage on {0}% of {2} on {1} turns.
        /// </summary>
        internal static string ProtectionEffectRuleText {
            get {
                return ResourceManager.GetString("ProtectionEffectRuleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        internal static string RejectButtonTitle {
            get {
                return ResourceManager.GetString("RejectButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        internal static string RestActionChat {
            get {
                return ResourceManager.GetString("RestActionChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Improved rest.
        /// </summary>
        internal static string RestActionImprovedRest {
            get {
                return ResourceManager.GetString("RestActionImprovedRest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scouting.
        /// </summary>
        internal static string RestActionScouting {
            get {
                return ResourceManager.GetString("RestActionScouting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рестарт.
        /// </summary>
        internal static string RestartButtonTitle {
            get {
                return ResourceManager.GetString("RestartButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rest.
        /// </summary>
        internal static string RestScreen_Title {
            get {
                return ResourceManager.GetString("RestScreen_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsButtonTitle {
            get {
                return ResourceManager.GetString("SettingsButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shield points: {0}.
        /// </summary>
        internal static string ShieldPointsLabelTemplate {
            get {
                return ResourceManager.GetString("ShieldPointsLabelTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short.
        /// </summary>
        internal static string ShortCombatSequenceText {
            get {
                return ResourceManager.GetString("ShortCombatSequenceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all enemies.
        /// </summary>
        internal static string SkillDirectionAllEnemiesText {
            get {
                return ResourceManager.GetString("SkillDirectionAllEnemiesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all ally.
        /// </summary>
        internal static string SkillDirectionAllFriendlyText {
            get {
                return ResourceManager.GetString("SkillDirectionAllFriendlyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enemies on the line.
        /// </summary>
        internal static string SkillDirectionAllLineEnemiesText {
            get {
                return ResourceManager.GetString("SkillDirectionAllLineEnemiesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all.
        /// </summary>
        internal static string SkillDirectionAllText {
            get {
                return ResourceManager.GetString("SkillDirectionAllText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to left ally.
        /// </summary>
        internal static string SkillDirectionLeftAllyText {
            get {
                return ResourceManager.GetString("SkillDirectionLeftAllyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all other ally.
        /// </summary>
        internal static string SkillDirectionOtherFriendlyText {
            get {
                return ResourceManager.GetString("SkillDirectionOtherFriendlyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all other.
        /// </summary>
        internal static string SkillDirectionOtherText {
            get {
                return ResourceManager.GetString("SkillDirectionOtherText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to random enemy.
        /// </summary>
        internal static string SkillDirectionRandomEnemyText {
            get {
                return ResourceManager.GetString("SkillDirectionRandomEnemyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to random ally.
        /// </summary>
        internal static string SkillDirectionRandomFriendlyText {
            get {
                return ResourceManager.GetString("SkillDirectionRandomFriendlyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to random enemy on the line.
        /// </summary>
        internal static string SkillDirectionRandomLineEnemyText {
            get {
                return ResourceManager.GetString("SkillDirectionRandomLineEnemyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to self.
        /// </summary>
        internal static string SkillDirectionSelfText {
            get {
                return ResourceManager.GetString("SkillDirectionSelfText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to target.
        /// </summary>
        internal static string SkillDirectionTargetText {
            get {
                return ResourceManager.GetString("SkillDirectionTargetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required {0} psy-energy.
        /// </summary>
        internal static string SkillManaCostTemplate {
            get {
                return ResourceManager.GetString("SkillManaCostTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        internal static string SkipButtonTitle {
            get {
                return ResourceManager.GetString("SkipButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press [SPACE] to skip.
        /// </summary>
        internal static string SkipMapPresentationHintText {
            get {
                return ResourceManager.GetString("SkipMapPresentationHintText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press [SPACE] to skip.
        /// </summary>
        internal static string SkipMapPresentationHintText_Duplicate_1_ {
            get {
                return ResourceManager.GetString("SkipMapPresentationHintText_Duplicate[1]", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not show anymore.
        /// </summary>
        internal static string SkipTutorialButtonTitle {
            get {
                return ResourceManager.GetString("SkipTutorialButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer: {0}.
        /// </summary>
        internal static string SlidingPuzzles_TimeCounterTemplate {
            get {
                return ResourceManager.GetString("SlidingPuzzles_TimeCounterTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turns: {0}.
        /// </summary>
        internal static string SlidingPuzzles_TurnsCounterTemplate {
            get {
                return ResourceManager.GetString("SlidingPuzzles_TurnsCounterTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not available in demo.
        /// </summary>
        internal static string StageNotImplementedInDemoText {
            get {
                return ResourceManager.GetString("StageNotImplementedInDemoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New game.
        /// </summary>
        internal static string StartNewGameButtonTitle {
            get {
                return ResourceManager.GetString("StartNewGameButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} imposed to {1}.
        /// </summary>
        internal static string StatusImposedNotificationTextTemplate {
            get {
                return ResourceManager.GetString("StatusImposedNotificationTextTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stun to {1} on {0}.
        /// </summary>
        internal static string StunEffectRuleText {
            get {
                return ResourceManager.GetString("StunEffectRuleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surrender.
        /// </summary>
        internal static string SurrenderButtonTitle {
            get {
                return ResourceManager.GetString("SurrenderButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch fullscreen.
        /// </summary>
        internal static string SwitchFullScreenButtonTitle {
            get {
                return ResourceManager.GetString("SwitchFullScreenButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch lang.
        /// </summary>
        internal static string SwitchLanguageButtonTitle {
            get {
                return ResourceManager.GetString("SwitchLanguageButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch music.
        /// </summary>
        internal static string SwitchMusicButtonTitle {
            get {
                return ResourceManager.GetString("SwitchMusicButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch resolution.
        /// </summary>
        internal static string SwitchResolutionButtonTitle {
            get {
                return ResourceManager.GetString("SwitchResolutionButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tactical potential exhausted.
        ///This hero can no longer act in the current battle..
        /// </summary>
        internal static string TacticalPotentialExhaustedIndicator {
            get {
                return ResourceManager.GetString("TacticalPotentialExhaustedIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To The Combat!.
        /// </summary>
        internal static string ToTheCombatButtonTitle {
            get {
                return ResourceManager.GetString("ToTheCombatButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Under construction.
        /// </summary>
        internal static string UnderConstructionModalContent {
            get {
                return ResourceManager.GetString("UnderConstructionModalContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aspiration: {0}.
        /// </summary>
        internal static string VoiceCombatStat_AspirationLableTemplate {
            get {
                return ResourceManager.GetString("VoiceCombatStat_AspirationLableTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conviction: {0}.
        /// </summary>
        internal static string VoiceCombatStat_ConvictionLableTemplate {
            get {
                return ResourceManager.GetString("VoiceCombatStat_ConvictionLableTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stamina: {0}.
        /// </summary>
        internal static string VoiceCombatStat_StaminaLableTemplate {
            get {
                return ResourceManager.GetString("VoiceCombatStat_StaminaLableTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xp Reward.
        /// </summary>
        internal static string XpRewardText {
            get {
                return ResourceManager.GetString("XpRewardText", resourceCulture);
            }
        }
    }
}
