name: Code Linter

on:
  workflow_dispatch

jobs:
  crop_images:
    name: Crop thumbnails from full spritesheet
    # Set the type of machine to run on
    runs-on: ubuntu-latest
    env:
      working-directory : ./
    steps:
      - uses: actions/checkout@v2

      - run: apt update
      - run: apt upgrade
      - run: apt install imagemagick
      
      - |
        # Указываем директорию, в которой будем искать файлы
        dir="/Rpg/Content/Content/Sprites/GameObjects/Characters"

        # Указываем маску файлов, которые будем обрабатывать
        mask="*thumbnail.txt"

        # Цикл поиска и обработки файлов
        for file in $(find $dir -name $mask); do
          # Проверяем, является ли найденный элемент файлом
          if [ -f "$file" ]; then
            # Обрабатываем файл (например, выводим его содержимое)
            echo "Processing file: $file"
            cat "$file"
          fi
        done