name: Code Lint Detection

on:
  pull_request

env:
  MGFXC_WINE_PATH: /home/runner/.winemonogame

jobs:

  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  resharper-core-lint:
    # Name the Job
    name: Clean up C# code base via R# CLT
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Setup Wine
        run: |
          sudo apt update
          sudo apt install wine64 p7zip-full
          wget -qO- https://raw.githubusercontent.com/MonoGame/MonoGame/master/Tools/MonoGame.Effect.Compiler/mgfxc_wine_setup.sh | sh
          cd ~/.winemonogame/drive_c/windows/system32
         
          DOTNET_URL="https://download.visualstudio.microsoft.com/download/pr/44d08222-aaa9-4d35-b24b-d0db03432ab7/52a4eb5922afd19e8e0d03e0dbbb41a0/dotnet-sdk-6.0.302-win-x64.zip"
          curl "https://download.visualstudio.microsoft.com/download/pr/44d08222-aaa9-4d35-b24b-d0db03432ab7/52a4eb5922afd19e8e0d03e0dbbb41a0/dotnet-sdk-6.0.302-win-x64.zip" --output "dotnet-sdk.zip"
         
          7z x "dotnet-sdk.zip" -y
         
          rm dotnet-sdk.zip

      - name: Restore dependencies
        run: dotnet restore
      
      - name: Build extentions
        run: dotnet build src/GameContent.Extensions/GameContent.Extensions.csproj --configuration Release

      - name: Setup ReSharper Command Line Tools
        run: dotnet tool install --global JetBrains.ReSharper.GlobalTools --version 2023.2.1

      # Building of the project is important step to resolve bin dependensies.
      # See docs https://www.jetbrains.com/help/resharper/CleanupCode.html#9663f16d
      - name: Build
        run: dotnet build --verbosity normal

      - name: Clean up codebase via ReSharper Command Line Tools
        run: jb cleanupcode --profile="Full Cleanup" Testament.sln
        working-directory: ${{env.working-directory}}

      - name: Write comment with changes
        run: |
          comment=""
          if [ -n "$(git status -s)" ]; then
          
              comment="Cleanup complete. There is follow changes:\n"
              comment+="\`\`\`\n"
              comment+=$(git status -s)
              comment+="\n\`\`\`"
            else
              comment="Cleanup complete. There is no changes."
            fi
            comment+="\n --cyber-goblin-marker-cleanup-resharper"
            echo $comment > cleanup_report.txt
        
      - name: Find Comment of goblin
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: 1
          body-includes: --cyber-goblin-marker-cleanup-resharper
        
      - uses: mshick/add-pr-comment@v2
        with:
          message-id: ${{ steps.fc.outputs.comment-id }}
          message-path: /home/runner/work/ewar/ewar/cleanup_report.txt