name: Code Linter

on:
  push:
    branches:
      - main
      - dev/**

env:
  MGFXC_WINE_PATH: /home/runner/.winemonogame

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  dotnet-format-core-lint:
    # Name the Job
    name: Clean up C# code base via dotnet-format
    # Set the type of machine to run on
    runs-on: ubuntu-latest
    env:
      working-directory : ./
    strategy:
      matrix:
        solution:
        - Rpg.Client
      fail-fast: false
    steps:
      - uses: actions/checkout@v2

      - run: git pull

      - run: dotnet tool install --global dotnet-format --version 5.1.250801

      - name: Format codebase ${{ matrix.solution }}
        run: dotnet-format Rpg.Client/${{ matrix.solution }}.sln --fix-whitespace --fix-style --verbosity detailed
        working-directory: ${{env.working-directory}}

      - name: Commit changes
        uses: EndBug/add-and-commit@v5
        with:
          message: "[Bot] Automated dotnet-format update"
          add: "*.cs"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  resharper-core-lint:
    # Name the Job
    name: Clean up C# code base via R# CLT
    # Set the type of machine to run on
    runs-on: ubuntu-latest
    env:
      working-directory : ./Rpg.Client/
    needs: [dotnet-format-core-lint]

    steps:
      - uses: actions/checkout@v2

      - run: git pull

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Setup Wine
        run: |
          sudo apt update
          sudo apt install wine64 p7zip-full
          wget -qO- https://raw.githubusercontent.com/MonoGame/MonoGame/master/Tools/MonoGame.Effect.Compiler/mgfxc_wine_setup.sh | sh
          cd ~/.winemonogame/drive_c/windows/system32
         
          DOTNET_URL="https://download.visualstudio.microsoft.com/download/pr/44d08222-aaa9-4d35-b24b-d0db03432ab7/52a4eb5922afd19e8e0d03e0dbbb41a0/dotnet-sdk-6.0.302-win-x64.zip"
          curl "https://download.visualstudio.microsoft.com/download/pr/44d08222-aaa9-4d35-b24b-d0db03432ab7/52a4eb5922afd19e8e0d03e0dbbb41a0/dotnet-sdk-6.0.302-win-x64.zip" --output "dotnet-sdk.zip"
         
          7z x "dotnet-sdk.zip" -y
         
          rm dotnet-sdk.zip

      - name: Setup ReSharper Command Line Tools
        run: dotnet tool install --global JetBrains.ReSharper.GlobalTools --version 2022.2.3

      # Building of the project is important step to resolve bin dependensies.
      # See docs https://www.jetbrains.com/help/resharper/CleanupCode.html#9663f16d
      - name: Build
        run: dotnet build Rpg.Client/Rpg.Client.sln --verbosity normal

      - name: Clean up codebase via ReSharper Command Line Tools
        run: jb cleanupcode --profile="Full Cleanup" Rpg.Client.sln
        working-directory: ${{env.working-directory}}

      - name: Commit changes
        uses: EndBug/add-and-commit@v5
        with:
          message: "[Bot] Automated ReSharper CLT update"
          add: "*.cs"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}