name: Publish

on:
  workflow_dispatch:
  push:
    branches:
      - 'demo/**'

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      MGFXC_WINE_PATH: /home/runner/.winemonogame
      GAME_VERSION: 0.2

    strategy:
      matrix:
        runtime:
          - win
          - linux
          - mac

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.18

    - name: Setup Wine
      run: |
        sudo apt update
        sudo apt install wine64 p7zip-full
        wget -qO- https://raw.githubusercontent.com/MonoGame/MonoGame/master/Tools/MonoGame.Effect.Compiler/mgfxc_wine_setup.sh | sh
        cd ~/.winemonogame/drive_c/windows/system32

        DOTNET_URL="https://download.visualstudio.microsoft.com/download/pr/44d08222-aaa9-4d35-b24b-d0db03432ab7/52a4eb5922afd19e8e0d03e0dbbb41a0/dotnet-sdk-6.0.302-win-x64.zip"
        curl "https://download.visualstudio.microsoft.com/download/pr/44d08222-aaa9-4d35-b24b-d0db03432ab7/52a4eb5922afd19e8e0d03e0dbbb41a0/dotnet-sdk-6.0.302-win-x64.zip" --output "dotnet-sdk.zip"

        7z x "dotnet-sdk.zip" -y

        rm dotnet-sdk.zip


    - name: Restore dependencies
      run: dotnet restore

    - name: Build extentions
      run: dotnet build src/GameContent.Extensions/GameContent.Extensions.csproj --configuration Release

    - name: Build
      run: dotnet build --verbosity normal

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Install GameBungle Tools
      run: dotnet tool install --global GameBundle

    - name: Publish
      run: gamebundle --source src/Client/Client.csproj --output "bin" --${{matrix.runtime}}

    - name: run number with offset
      id: game-version
      env:
        run_number: ${{ github.run_number }}
        base_number: 71
      run: echo "full=$GAME_VERSION.$(($run_number+$base_number))" >> $GITHUB_OUTPUT

    - run: echo ${{ steps.game-version.outputs.full }}

    - name: Get current time
      uses: srfrnk/current-time@master
      id: current-time
      with:
        format: YYYY-MM-DD
    
    - name: Write version to file
      uses: DamianReeves/write-file-action@v1.2
      with:
        path: bin/${{matrix.runtime}}/version.txt
        contents: |
          ver ${{ steps.game-version.outputs.full }}
          ${{ steps.current-time.outputs.formattedTime }}
          ${{ github.sha }}
        write-mode: overwrite

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: ewar-${{ matrix.runtime }}-v${{ steps.game-version.outputs.full }}-${{ steps.current-time.outputs.formattedTime }}
        path: bin
