name: Publish

on:
  workflow_dispatch:
  push:
    branches:
      - 'demo/**'
      - fix/game-version

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      MGFXC_WINE_PATH: /home/runner/.winemonogame

    strategy:
      matrix:
        runtime:
          - win
          - linux
          - mac

    steps:
    - uses: actions/checkout@v2

    - name: Build Number (with base)
      uses: mlilback/build-number@v1.0.1
      id: build-number
      with:
        base: 71
        run-id: ${GITHUB_RUN_NUMBER}

    - name: run number with offset
      id: game-version
      env:
        run_number: ${{ github.run_number }}
        base_number: 71
      run: echo "full=0.2-dev.$(($run_number+$base_number)) >> $GITHUB_OUTPUT

    - run: echo ${{ steps.game-version.outputs.full }}

    
    - name: Write version to file
      uses: DamianReeves/write-file-action@v1.2
      env:
        F_TIME: "${{ steps.current-time.outputs.formattedTime }}"
        GAME_VERSION: "0.2-dev.${{ steps.build-number.outputs.build-number }}"
      with:
        path: bin/${{matrix.runtime}}/version.txt
        contents: |
          ver ${{ env.GAME_VERSION }}
          ${{ env.F_TIME }}
          ${{ github.sha }}
        write-mode: overwrite

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      env:
        F_TIME: "${{ steps.current-time.outputs.formattedTime }}"
        GAME_VERSION: "0.2-dev.${{ steps.build-number.outputs.build-number }}"
      with:
        name: ewar-${{ matrix.runtime }}-v${{ env.F_TIME }}-${{ env.F_TIME }}
        path: bin
